### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by iyangim** [skandasoft/browser-plus#100]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/urimalsoft/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/Users/urimalsoft/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/Users/urimalsoft/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
     -4:43.6.0 settings-view:open (atom-text-editor.editor.is-focused.power-mode)
     -4:00.5.0 atom-beautify:beautify-editor (atom-text-editor.editor.power-mode.is-focused)
     -3:56.6.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:22.7.0 pane:split-left (atom-text-editor.editor.mini.is-focused)
     -0:49.3.0 browser-plus:open (atom-text-editor.editor.power-mode.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0
autocomplete-ionic-framework, v0.2.2
browser-plus, v0.0.67
pigments, v0.31.2

# Dev
No dev packages
```

**Comment by Akumetsu-Dev** [comment]
[Enter steps to reproduce below:]

1. Open Html
2. Try to live a html file

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67


### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:809:27)
    at atom-workspace.module.exports.WorkspaceElement.handleFocus (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace-element.js:127:41)
```

### Commands

```
     -0:07.9.0 encoding-selector:show (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "browser-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.67
browser-plus-block, v0.0.4
browser-plus-zoom, v0.0.1
file-icons, v1.7.17
navigate, v0.1.16
open-in-browsers, v0.0.19
pp, v0.0.1
pp-js, v0.0.2
preview-plus, vundefined

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
#98
