### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by madka515** [skandasoft/browser-plus#101]
**Atom Version:** 1.8.0
**System:** Windows10
**Thrown From:** browser-plus package, v0.0.67

### Stack Trace
Cannot read property 'get' of undefined

> TypeError: Cannot read property 'get' of undefined
    at Object.module.exports.BrowserPlus.activate (file:///C:/Users/SEKIYA/.atom/packages/browser-plus/lib/browser-plus.coffee:37:64)
    at Package.module.exports.Package.activateNow (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:183:20)
    at C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\package-manager.js:497:46)
    at C:\Users\SEKIYA\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:754:28

I need help...

**Comment by skandasoft** [comment]
looks like the same as #97 will track from there. Can you uninstall and reinstall. looks like jStorage is not getting installed.
