### ISSUE TITLE
I hope that this will help fix this issue soon

### ISSUE THREAD

**Issue by dutch45** [skandasoft/browser-plus#102]
module.js:340
Hide Stack Trace
Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Philip/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (file:///C:/Users/Philip/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/Philip/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.activeItemChanged (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:282:22)
    at Pane.module.exports.Pane.addItem (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:494:14)
    at Pane.module.exports.Pane.activateItem (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:428:14)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Philip\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:658:19)

**Comment by wBureshGitHub** [comment]
I'm experiencing the same, using Debian Jessie.

**Comment by skandasoft** [comment]
#98
