### ISSUE TITLE
Uncaught Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'

### ISSUE THREAD

**Issue by fusion809** [skandasoft/browser-plus#105]
Hi,

This package is generating an error for me. If you are wondering what's with Electron 1.3.1 being used instead of 0.37.8 (which comes bundled with Atom 1.9.2 by default) it's because I'm using a special build of Atom that uses the latest Electron (see my https://github.com/fusion809/arch-atom repo and the upstream repo https://github.com/tensor5/arch-atom). 

[Enter steps to reproduce below:]

1. Right-click on an opened pane
2. Select 'Open Browser-Plus' from the context menu

**Atom Version**: 1.9.2
**Electron Version**: 1.3.1
**System**: "Arch Linux"
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.73

### Stack Trace

Uncaught Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'

```
At module.js:442

Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/usr/lib/electron/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib/atom-bleeding/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Object.<anonymous> (/home/fusion809/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/fusion809/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/fusion809/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/lib/atom-bleeding/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/lib/atom-bleeding/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/usr/lib/atom-bleeding/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom-bleeding/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom-bleeding/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/usr/lib/atom-bleeding/src/pane.js:570:20)
    at Pane.module.exports.Pane.destroyItem (/usr/lib/atom-bleeding/src/pane.js:639:16)
    at atom-tabs.TabBarView.onClick (/usr/lib/atom-bleeding/node_modules/tabs/lib/tab-bar-view.js:692:17)
```

### Commands

```
     -0:10.8.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.octave": [
        ".m"
      ],
      "source.python": [
        "BUCK"
      ],
      "source.shell.install": [
        ".install"
      ],
      "source.vala": [
        ".vala",
        ".vapi"
      ]
    },
    "disabledPackages": [
      "language-gfm",
      "language-shellscript",
      "project-manager"
    ],
    "excludeVcsIgnoredPaths": false,
    "projectHome": "/home/fusion809/GitHub/mine",
    "themes": [
      "fusion-ui",
      "dark-bint-syntax"
    ]
  },
  "browser-plus": {
    "homepage": "browser-plus://localhost:4000",
    "live": 1
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.3 (inactive)
archive-view, v0.61.1 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-oss-license, v1.0.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-clang, v0.9.4 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-modules, v1.5.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-sass, v0.1.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
browser-plus, v0.0.73 (active)
busy, v0.6.0 (active)
command-palette, v0.38.0 (inactive)
dark-bint-syntax, v0.8.9 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
file-icons, v1.7.17 (active)
find-and-replace, v0.201.0 (inactive)
fusion-ui, v0.11.1 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2-0 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
ionide-webview, v1.0.3 (active)
keybinding-resolver, v0.35.0 (active)
language-ada, v1.1.0 (active)
language-asciidoc, v1.5.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-debian, v0.2.1 (active)
language-docker, v1.1.6 (active)
language-gentoo, v0.9.0 (inactive)
language-gfm2, v0.92.2 (active)
language-git, v0.15.0 (active)
language-gnuplot-atom, v0.2.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-ini-desktop, v1.18.3 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-latex, v0.6.1 (active)
language-less, v0.29.5 (active)
language-liquid, v0.5.1 (active)
language-lisp, v0.2.0 (active)
language-lua, v0.9.4 (active)
language-make, v0.22.2 (active)
language-matlab-octave, v0.1.1 (active)
language-mediawiki, v2.0.0 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-pascal, v0.18.1 (active)
language-patch2, v1.0.0 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-rpm-spec, v0.11.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-rust, v0.4.6 (active)
language-sass, v0.56.0 (active)
language-scala, v1.1.6 (active)
language-solus, v0.2.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-unix-shell, v0.37.5 (active)
language-vala-modern, v0.3.2 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)
latex-plus, v0.8.7 (inactive)
line-ending-selector, v0.5.0 (active)
linter, v1.11.14 (active)
linter-coffeescript, v1.0.0 (active)
linter-cppcheck, v0.2.0 (active)
linter-gcc, v0.6.15 (active)
linter-jsonlint, v1.3.0 (active)
markdown-toc, v0.4.1 (inactive)
markdown-writer, v2.5.1 (inactive)
material-ui, v1.0.9 (inactive)
minimap, v4.24.7 (active)
monokai-flat, v1.0.1 (inactive)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
package-sync, v1.1.0 (active)
pigments, v0.31.2 (active)
snippets, v1.0.2 (active)
svg-preview, v0.8.0 (active)
timecop, v0.33.2 (active)
tool-bar, v1.0.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
dark-bint-syntax, v0.8.9 (active)
fusion-ui, v0.11.1 (active)
about-arch, v1.6.2 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
find-and-replace, v0.201.0 (inactive)
grammar-selector, v0.48.2-0 (active)
keybinding-resolver, v0.35.0 (active)
language-archlinux, v0.8.8 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
settings-view, v0.241.1 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.100.0 (active)
terminal-fusion, v2.3.1 (active)
tree-view, v0.208.2 (active)

# Dev
No dev packages
```

**Comment by handicraftsman** [comment]
Same:
[Enter steps to reproduce below:]

1. Same
2. Profit?

**Atom Version**: 1.10.0-beta1
**Electron Version**: 0.37.8
**System**: "Manjaro Linux" (preconfigured arch-linux)
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.73


### Stack Trace

Uncaught Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'

```
At module.js:341

Error: Cannot find module '../node_modules/jquery-ui/autocomplete.js'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/local/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/local/share/atom-beta/resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/local/share/atom-beta/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/usr/local/share/atom-beta/resources/app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:570:20)
    at Pane.module.exports.Pane.destroyItem (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:639:16)
    at atom-tabs.TabBarView.onClick (/usr/local/share/atom-beta/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:692:17)
```

### Commands

```
     -0:02.3.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "atom-bootstrap3",
      "atom-bootstrap4",
      "archive-view",
      "atom-grammar-test",
      "autosave",
      "bookmarks",
      "language-clojure",
      "language-csharp",
      "language-git",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-yaml",
      "link",
      "spell-check",
      "language-toml",
      "open-on-github",
      "autoclose-html"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.0 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (inactive)
atom-html-preview, v0.1.22 (active)
autoclose-html, v0.23.0 (inactive)
browser-plus, v0.0.73 (active)
file-icons, v1.7.17 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Please check the latest patch

**Comment by handicraftsman** [comment]
Still not works. Still in same file

**Comment by skandasoft** [comment]
can you post the error pls

**Comment by tkalmi** [comment]
I'm seeing the same error.

[Enter steps to reproduce below:]

Right-click on an opened pane
Select 'Open Browser-Plus' from the context menu
__Atom Version__: 1.9.4
__Electron Version__: Not sure? Dev tools says `0.37.8` when I write `process.versions.electron` to the console.
__System__: "Windows 10"
__Thrown From__: browser-plus package, v0.0.74

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\tkalmi.atom\packages/browser-plus/node_modules/jquery-ui/autocomplete.js'

    Error: Cannot find module 'C:\Users\tkalmi\.atom\packages/browser-plus/node_modules/jquery-ui/autocomplete.js'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/tkalmi/.atom/packages/browser-plus/lib/browser-plus-view.coffee:6:1)
    at Object.<anonymous> (file:///C:/Users/tkalmi/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/tkalmi/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\pane.js:833:27)
    at C:\Users\tkalmi\AppData\Local\atom\app-1.9.4\resources\app.asar\src\workspace.js:540:18

**Comment by skandasoft** [comment]
cleaned up..can you do a fresh install of browser-plus

**Comment by tkalmi** [comment]
Thanks! browser-plus works now at least on my end.

**Comment by fusion809** [comment]
Fixed. Although it allowed me to find that issue #91 is alive and well.

**Comment by handicraftsman** [comment]
Still:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.0-beta1
**Electron Version**: 0.37.8
**System**: "Manjaro Linux"
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.75


### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:341

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/usr/local/share/atom-beta/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/local/share/atom-beta/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/usr/local/share/atom-beta/resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/ancient/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/local/share/atom-beta/resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/local/share/atom-beta/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/usr/local/share/atom-beta/resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/usr/local/share/atom-beta/resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/usr/local/share/atom-beta/resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/local/share/atom-beta/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:833:27)
    at Pane.module.exports.Pane.focus (/usr/local/share/atom-beta/resources/app.asar/src/pane.js:236:21)
    at atom-pane.<anonymous> (/usr/local/share/atom-beta/resources/app.asar/src/pane-element.js:50:23)
```

### Commands

```
     -1:09.4.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-light-syntax.theme-one-light-ui)
     -0:04.5.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "atom-bootstrap3",
      "atom-bootstrap4",
      "archive-view",
      "atom-grammar-test",
      "autosave",
      "bookmarks",
      "language-clojure",
      "language-csharp",
      "language-git",
      "language-go",
      "language-java",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-yaml",
      "link",
      "spell-check",
      "language-toml",
      "open-on-github",
      "autoclose-html",
      "vim-mode"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.2 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (inactive)
atom-html-preview, v0.1.22 (active)
autoclose-html, v0.23.0 (inactive)
browser-plus, v0.0.75 (active)
file-icons, v1.7.18 (active)
keyboard-localization, v1.4.18 (active)
vim-mode, v0.65.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by handicraftsman** [comment]
So, reopen.

**Comment by skandasoft** [comment]
did you uninstall the browserplus  completely and reinstall as it has jquery-ui in the node_modules

**Comment by handicraftsman** [comment]
I am not JS developer (but learning JS just now, but i fully reinstalled (as you said) this plugin)

**Comment by skandasoft** [comment]
tracking from #98
