### ISSUE TITLE
Open-In-Browser: Instant error

### ISSUE THREAD

**Issue by laynefaler** [skandasoft/browser-plus#106]
![screen shot 2016-08-03 at 10 25 05 am](https://cloud.githubusercontent.com/assets/14255968/17375143/a991d36e-5964-11e6-8f79-f941ad4d2aa2.png)

![screen shot 2016-08-03 at 10 17 18 am](https://cloud.githubusercontent.com/assets/14255968/17374895/90a95152-5963-11e6-9801-ffbff80964af.png)

error:
TypeError: Cannot read property 'get' of undefined
    at Object.module.exports.BrowserPlus.activate (/Users/laynefaler/.atom/packages/browser-plus/lib/browser-plus.coffee:37:64)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:760:28

Steps to Reproduce:
1. Install browser-plus
2. Open Atom

Versions:

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.1

Atom    : 1.9.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**\* This error still exists with the new patch. ***

**Comment by skandasoft** [comment]
can you tell what is there in this location /Users/laynefaler/.atom/packages/browser-plus/node_modules

**Comment by skandasoft** [comment]
or simply try installing npm install jstorage at /Users/laynefaler/.atom/packages/browser-plus/

**Comment by lfaler** [comment]
This is what's in node_modules:

JSON2                
jquery-ui            
theorist
atom-space-pen-views 
jstorage
jquery               
lodash

And I installed jstorage, installing jstorage didn't fix the issue

![screen shot 2016-08-04 at 11 26 50 am](https://cloud.githubusercontent.com/assets/14255968/17413567/8aef9e0a-5a36-11e6-9013-25471c3c3890.png)

Error:
TypeError: Cannot read property 'get' of undefined
    at Object.module.exports.BrowserPlus.activate (/Users/laynefaler/.atom/packages/browser-plus/lib/browser-plus.coffee:37:64)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:760:28

**Comment by skandasoft** [comment]
may be try the latest patch.

**Comment by lfaler** [comment]
Latest patch of Atom or the package? Because I'm sure I'm on both now

**Comment by skandasoft** [comment]
latest package of browser-plus. npm uninstall browser-plus and npm install browser-plus

**Comment by lfaler** [comment]
This is the lastest patch on browser-plus, this whole error has been on the latest patch of browser-plus

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
