### ISSUE TITLE
'Cheerio' Error

### ISSUE THREAD

**Issue by Akumetsu-Dev** [skandasoft/browser-plus#109]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.75

### Stack Trace

Uncaught Error: Cannot find module 'cheerio'

```
At module.js:341

Error: Cannot find module 'cheerio'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\native-compile-cache.js:50:27)
    at Function.module.exports.BrowserPlusView.checkBase (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:357:15)
    at Function.module.exports.BrowserPlusView.content (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:31:36)
    at Function.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:156:31)
    at Function.View.buildHtml (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:123:10)
    at BrowserPlusView.View [as constructor] (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:155:33)
    at new BrowserPlusView (file:///C:/Users/Walddys Emmanuel/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:833:27)
    at atom-workspace.module.exports.WorkspaceElement.handleFocus (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.9.8\resources\app.asar\src\workspace-element.js:127:41)
```

### Commands

```
     -0:32.2.0 core:close (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-html-preview, v0.1.22 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-paths, v1.0.2 (active)
autoprefixer, v3.2.0 (inactive)
browser-plus, v0.0.75 (active)
browser-plus-block, v0.0.4 (active)
browser-plus-zoom, v0.0.1 (active)
close-tags, v0.6.0 (inactive)
color-picker, v2.2.2 (active)
double-tag, v0.4.0 (active)
file-icons, v1.7.18 (active)
highlight-line, v0.11.1 (active)
html-to-css, v0.2.2 (inactive)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (active)
linter-jscs, v4.0.5 (active)
linter-jshint, v2.1.0 (active)
linter-tidy, v2.2.0 (active)
minimap, v4.24.7 (active)
minimap-bookmarks, v0.3.1 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-pigments, v0.2.1 (active)
minimap-selection, v4.4.0 (active)
pp, v0.0.1 (active)
preview-plus, v1.2.7 (active)
script, v3.8.3 (inactive)
tree-view-copy-relative-path, v1.0.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Assuming should have fixed the error..as there is no response.
