### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete

### ISSUE THREAD

**Issue by pwaila** [skandasoft/browser-plus#116]
[Enter steps to reproduce below:]
1. Write some python code in atom editor
2. Write click on code editor and open Browser-Plus

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.76
### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:341

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/pranavwaila/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/Users/pranavwaila/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/Users/pranavwaila/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:833:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/Users/pranavwaila/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```
### Commands

```
  4x -5:31.9.0 terminal-plus:context-close (i.icon.icon-terminal)
     -4:28.1.0 browser-plus:open (atom-text-editor.editor.is-focused)
  9x -4:12.1.0 core:confirm (atom-pane.pane.active)
     -3:10.7.0 tree-view:reveal-active-file (atom-text-editor.editor)
     -0:35.8.0 core:cancel (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-pyspark",
      "syntax-theme-auto-changer"
    ],
    "themes": [
      "one-dark-ui",
      "pastel-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-pyspark, v0.2.6 (inactive)
autocomplete-python, v1.8.6 (active)
browser-plus, v0.0.76 (active)
console-panel, v0.2.0 (active)
github-atom-light-syntax, v0.2.0 (inactive)
Hydrogen, v0.14.0 (active)
jupyter-notebook, v0.0.9 (active)
language-particle, v0.3.4 (active)
script-runner, v1.8.4 (active)
syntax-theme-auto-changer, v0.9.4 (inactive)
terminal-plus, v0.14.5 (active)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
