### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by James-Yan** [skandasoft/browser-plus#120]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.76
### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:341

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/JamesYan/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (file:///C:/Users/JamesYan/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/JamesYan/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Pane.module.exports.Pane.activate (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\pane.js:837:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\notifications\lib\notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\notifications\lib\notification-element.js:248:19)
    at C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\notifications\lib\notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at Notification.module.exports.Notification.dismiss (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\src\notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\notifications\lib\notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (C:\Users\JamesYan\AppData\Local\atom\app-1.11.1\resources\app.asar\node_modules\notifications\lib\notification-element.js:147:26)
```
### Commands

```
     -2:08.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:06.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:37.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:36.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:36.9.0 browser-plus:open (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "no"
  },
  "browser-plus": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (inactive)
atom-ternjs, v0.15.0 (active)
atomic-chrome, v0.3.0 (active)
browser-plus, v0.0.76 (active)
goto-definition, v1.1.19 (active)
linter, v1.11.18 (active)
linter-php, v1.2.0 (active)
php-debug, v0.2.3 (active)
svn, v0.0.13 (active)
symbols-list, v2.3.1 (active)
tortoise-svn, v0.5.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by wBureshGitHub** [comment]
I get the same (atom: 1.11.1, browser-plus: 0.0.76, Debian-Jessie

**Comment by skandasoft** [comment]
Check the latest patch/FAQ
