### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by Bobspadger** [skandasoft/browser-plus#121]
[Enter steps to reproduce below:]

1.Install plugin
2. Attempt to activate

**Atom Version**: 1.11.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.12
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.76
### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:341

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/alexhellier/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/Users/alexhellier/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/Users/alexhellier/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:837:27)
    at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:666:33)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```
### Commands

```
  3x -0:12.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:05.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 browser-plus:open (atom-text-editor.editor)
     -0:03.4.0 core:confirm (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {
    "telemetryConsent": "no"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (inactive)
atom-html-preview, v0.1.22 (active)
browser-plus, v0.0.76 (active)
color-picker, v2.2.2 (active)
css-to-inline, v1.1.0 (inactive)
linter, v1.11.18 (active)
linter-htmlhint, v1.3.0 (active)
my-theme-syntax, v0.0.0 (inactive)
xml-tools, v0.2.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Masquerade-Circus** [comment]
This will work: 

1. Install the package to Atom. 
2. Clone or download the package. 
3. Go tho the cloned package dir and do an npm install. 
4. Copy all the cloned package files to .atom/packages/browser-plus. 
5. Reopen Atom.

**Comment by pdiddles03** [comment]
Doing a hack to make a plugin work  isn't the answer.

**Comment by evacchi** [comment]
btw doing what @Masquerade-Circus suggest should be equivalent to doing `apm install skandasoft/browser-plus`. Don't know if it fixes the bug, though, didn't test.

**Comment by 00buggy00** [comment]
I'm very new to atom, but I was looking for something different and a little more html friendly than Xcode (I actually love Xcode, but there isn't a live preview feature).  I've been integrating GitHub into my projects, too very recently and heard about Atom at the 2016 GitHub Universe.  During my research, I saw browser-plus and clicked on install from within the app; however, got this issue.  Using terminal I entered `app install skandasoft/browser-plus`  as @evacchi stated previously.  This worked!  package successfully installed and working appropriately.  Not sure why the install button in the app isn't working though.

**Comment by Gui38** [comment]
Hello everybody
having same problem on windows 10 (and liking it)
after struggling with PATH (and loving it) I managed to get apm work
BUT "apm install skandasoft/browser-plus :"
---------------------------------
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Le fichier spécifié est introuvable.       //trad: unable to find specified file for specified model//
Cloning https://github.com/skandasoft/browser-plus.git failed
Installing modules done
Cannot read property 'getReferenceTarget' of null
---------------------------------
still trying to get that promising nested browser do you have any hints?
Thank you ! Gui

**Comment by VProfirov** [comment]
Can someone explain in more detail the 2nd and 3th step ?
> Clone or download the package.
Go tho the cloned package dir and do an npm install.

**Comment by evacchi** [comment]
@VProfirov use `apm install skandasoft/browser-plus`. @00buggy00 has confirmed it works. It is equivalent to @Masquerade-Circus' solution, but less "manual"

**Comment by respok** [comment]
would it not be easier just to fix the button?

**Comment by cliffordfajardo** [comment]
@VProfirov: if you're on Mac this should work.

-  go to the settings of the package `browser-plus` & click on the `view code` button. This should launch a new instance of Atom with the browser plus package. 

- next, option click the name of the package in the tree view & select "Show in Finder". Drag the folder to your terminal application to get the path of the package & `cd` into it. Once your at the root of the folder `browser-plus` do the `npm install`

**Comment by Aydee221** [comment]
@cliffordfajardo, thanks for the idea. I'm also having the "Cannot find module 'jquery-ui/autocomplete'" error (obviously), but your fix didn't work for me. Any other ideas? Everyone else, did you have any luck?

**Comment by respok** [comment]
@cliffordfajardo this didn't work for me either.

**Comment by skandasoft** [comment]
Check the latest patch. Check FAQ for more.
