### ISSUE TITLE
Uncaught TypeError: this.model.browserPlus.getBrowserPlusUrl is not a function

### ISSUE THREAD

**Issue by Toby56** [skandasoft/browser-plus#125]
**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Microsoft Windows 8.1
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.86

### Stack Trace

Uncaught TypeError: this.model.browserPlus.getBrowserPlusUrl is not a function

```
At G:\Applications\Atom\.atom\packages\browser-plus\lib\browser-plus-view.coffee:378

TypeError: this.model.browserPlus.getBrowserPlusUrl is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.goToUrl (file:///E:/Applications/Atom/.atom/packages/browser-plus/lib/browser-plus-view.coffee:378:34)
    at HTMLInputElement.<anonymous> (file:///E:/Applications/Atom/.atom/packages/browser-plus/lib/browser-plus-view.coffee:345:12)
    at HTMLInputElement.dispatch (G:\Applications\Atom\.atom\packages\browser-plus\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (G:\Applications\Atom\.atom\packages\browser-plus\node_modules\space-pen\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -3:50.5.0 core:focus-previous (webview.native-key-bindings)
     -3:33 core:backspace (atom-text-editor.editor.is-focused)
     -3:31.2.0 core:save (atom-text-editor.editor.is-focused)
     -3:21.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:20.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "tab-preview",
      "file-icons",
      "linter"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "browser-plus"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "flexible-ui",
      "bionis-dark-syntax"
    ],
    "warnOnLargeFileLimit": 2
  }
}
```

### Installed Packages

```coffee
# User
atom-hipster-ui, v0.1.0 (inactive)
atom-html-preview, v0.1.22 (active)
atom-live-server, v1.2.5 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.8 (inactive)
atom-minify, v0.7.5 (active)
atomic-ui, v1.5.2 (inactive)
bionis-dark-syntax, v1.1.0 (active)
bionis-syntax, v1.1.0 (inactive)
browser-plus, v0.0.86 (active)
browser-plus-zoom, v0.0.2 (active)
chrome-color-picker, v0.8.0 (inactive)
emmet, v2.4.3 (active)
ficus-dark-syntax, v1.1.0 (inactive)
ficus-syntax, v1.1.0 (inactive)
flexible-ui, v0.10.5 (active)
genesis-ui, v0.5.0 (inactive)
github-atom-dark-syntax, v0.2.0 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
isotope-light-ui, v2.2.6 (inactive)
isotope-ui, v2.7.1 (inactive)
linter, v1.11.18 (inactive)
linter-csslint, v1.3.3 (active)
linter-write-good, v0.8.0 (active)
linter-xo, v0.21.0 (active)
minimap, v4.25.6 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
nord-atom-ui, v0.8.1 (inactive)
nucleus-dark-ui, v0.10.18 (inactive)
peacock-syntax, v1.4.0 (inactive)
pigments, v0.37.0 (active)
smart-tab-name, v1.0.5 (active)
solarized-dark-ui, v0.3.1 (inactive)
solarized-light-ui, v0.1.0 (inactive)
steam-pirate-ui, v0.6.1 (inactive)
svg-preview, v0.10.0 (active)
tab-title, v0.3.3 (active)
unfancy-file-icons, v0.10.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you tell how to recreate this. I did release a patch though

**Comment by skandasoft** [comment]
check the latest patch ....if still issue try  running apm rebuild-module-cache on the atom packages directory
