### ISSUE TITLE
Uncaught TypeError: Cannot read property 'target' of undefined

### ISSUE THREAD

**Issue by Jense5** [skandasoft/browser-plus#128]
This error occurs whenever I right click within atom. It doesn't matter where it is, even in the filetree for example. It happens when the package is installed. A browser window shouldn't even be open. It just happens all the time and therefore I am unable to right click anywhere.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.87

### Stack Trace

Uncaught TypeError: Cannot read property 'target' of undefined

```
At /Users/bernard/.atom/packages/browser-plus/lib/browser-plus-model.coffee:24

TypeError: Cannot read property 'target' of undefined
  at Object.HTMLEditor.item.shouldDisplay (/Users/bernard/.atom/packages/browser-plus/lib/browser-plus-model.coffee:24:38)
  at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:129:19)
  at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:87:33)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:187:27)
  at window.requestAnimationFrame (/Users/bernard/.atom/packages/nuclide/pkg/nuclide-file-tree/lib/main.js:89:125)

```

### Commands

```
  2x -6:46 core:close (atom-text-editor.editor.is-focused)
     -6:41.9.0 settings-view:open (atom-text-editor.editor.is-focused)
  2x -6:35.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:54.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 10x -5:52.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -5:39.7.0 git-plus:diff (atom-text-editor.editor.is-focused)
     -5:23.9.0 open-on-github:history (atom-text-editor.editor.is-focused)
     -4:01.7.0 open-on-github:blame (atom-text-editor.editor.is-focused)
     -0:36.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:18 browser-plus:open (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".hgrc",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "linter"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "atom-monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-darcula, v0.2.0 (inactive)
atom-monokai, v0.10.4 (active)
browser-plus, v0.0.87 (active)
dracula-theme, v1.2.8 (inactive)
git-plus, v5.25.5 (active)
haskell-grammar, v0.4.0 (active)
highlight-selected, v0.11.2 (active)
language-babel, v2.48.5 (active)
language-graphql, v0.7.0 (active)
language-ini, v1.16.0 (active)
language-ocaml, v1.1.2 (active)
language-swift, v0.5.0 (active)
language-thrift, v1.0.2 (active)
linter, v1.11.18 (inactive)
linter-eslint, v8.0.0 (active)
linter-write-good, v0.8.0 (active)
merge-conflicts, v1.4.4 (active)
nord-atom-syntax, v0.4.0 (inactive)
nord-atom-ui, v0.9.0 (inactive)
nuclide, v0.188.0 (active)
nuclide-format-js, v0.0.36 (inactive)
sort-lines, v0.14.0 (inactive)
tool-bar, v1.0.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (active)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by usirin** [comment]
Same happened to me today. Any updates?

**Comment by danielniquet** [comment]
Same for me...

**Comment by andreiserea** [comment]
Same for me

**Comment by skandasoft** [comment]
check the latest patch ....if still issue try  running apm rebuild-module-cache on the atom packages directory

**Comment by diman95** [comment]
version 0.0.97
did apm rebuild-module-cache

```
***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:43
Hide Stack Trace
TypeError: Cannot read property 'target' of undefined
    at Object.HTMLEditor.item.shouldDisplay (***/.atom/packages/browser-plus/lib/browser-plus-model.coffee:24:17)
    at ContextMenuManager.module.exports.ContextMenuManager.cloneItemForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:142:25)
    at ContextMenuManager.module.exports.ContextMenuManager.templateForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:100:39)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:200:33)
    at a.sub.nextAnimationFrame.repeat.last.subscribe [as _next] (***/nuclide/0.236.63305782/nuclide/pkg/nuclide-file-tree/lib/main.js:162:22)
    at a.__tryOrUnsub (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:43:337)
    at a.next (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:42:227)
    at a._next (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:393)
    at a.next (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:64)
    at a._complete (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:189:331)
    at a.complete (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:228)
    at a._complete (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:529)
    at a.complete (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:40:228)
    at a.complete (***/nuclide/0.235.62603218/nuclide/node_modules/rxjs/bundles/Rx.min.js:207:175)
    at requestAnimationFrame (***/nuclide/0.236.63305782/nuclide/modules/nuclide-commons/observable.js:297:14)
```

**Comment by skandasoft** [comment]
Could you check the latest patch
