### ISSUE TITLE
Failed to activate the browser-plus package

### ISSUE THREAD

**Issue by Tikam02** [skandasoft/browser-plus#129]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.87

### Stack Trace

Failed to activate the browser-plus package

```
At Cannot read property 'jStorage' of undefined

TypeError: Cannot read property 'jStorage' of undefined
    at Object.module.exports.BrowserPlus.activate (file:///F:/IDE/atom/AtomPortable/Data/atom/packages/browser-plus/lib/browser-plus.coffee:38:55)
    at Package.module.exports.Package.activateNow (F:\IDE\atom\App\Atom\resources\app.asar\src\package.js:183:20)
    at F:\IDE\atom\App\Atom\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (F:\IDE\atom\App\Atom\resources\app.asar\src\package.js:92:15)
    at F:\IDE\atom\App\Atom\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (F:\IDE\atom\App\Atom\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (F:\IDE\atom\App\Atom\resources\app.asar\src\package-manager.js:538:21)
    at F:\IDE\atom\App\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:460:29
    at exit (F:\IDE\atom\App\Atom\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (F:\IDE\atom\App\Atom\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (F:\IDE\atom\App\Atom\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
  2x -4:29.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:25.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:14 core:select-all (atom-text-editor.editor.is-focused)
     -4:13.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:43.4.0 core:paste (atom-text-editor.editor.is-focused)
 25x -3:08.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:00.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:54.9.0 linter:next-error (atom-workspace.workspace.scrollbars-visible-always.theme-nord-atom-syntax.theme-solarized-seti-ui)
  3x -0:44.8.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
     -0:42.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  3x -0:36 core:backspace (atom-text-editor.editor.mini.is-focused)
  6x -0:19 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  2x -0:09.9.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icons",
      "language-gfm"
    ],
    "projectHome": "F:\\projects",
    "telemetryConsent": "limited",
    "themes": [
      "solarized-seti-ui",
      "nord-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
aligner-css, v1.2.0 (active)
aligner-javascript, v1.0.0 (active)
angular-2-typeScript-snippets, v0.6.3 (active)
angular-bootstrap, v1.0.1 (inactive)
angular2-snippets, v0.3.0 (active)
angular2-snippets-atom, v0.7.0 (active)
angularjs, v0.3.5 (active)
animate-css, v0.1.4 (active)
ariake-dark-syntax, v0.0.6 (inactive)
astronomical-ui, v0.22.5 (inactive)
atom-beautify, v0.29.13 (inactive)
atom-bemmet, v2.0.0 (inactive)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (active)
atom-bugs, v0.19.9 (active)
atom-code2html, v0.1.0 (inactive)
atom-css-class-checker, v0.4.3 (inactive)
atom-css-comb, v3.1.0 (inactive)
atom-css-unit-converter, v1.1.1 (inactive)
atom-darcula, v0.2.0 (inactive)
atom-debugger, v0.1.6 (inactive)
atom-formatter-jsbeautify, v1.1.2 (active)
atom-gist-dev, v0.3.1 (inactive)
atom-github-issues, v0.4.3 (active)
atom-html-preview, v0.1.22 (active)
atom-html-templates, v0.1.3 (inactive)
atom-htmltidy, v5.1.0 (active)
atom-idiomatic-comments-css-snippets, v0.1.0 (active)
atom-javascript-console-snippets, v0.10.0 (active)
atom-material-syntax, v0.4.6 (inactive)
atom-material-ui, v1.3.8 (inactive)
atom-minify, v0.7.5 (active)
atom-monokai, v0.10.4 (inactive)
atom-prettify, v0.1.3 (inactive)
atom-react-native-css, v1.1.3 (active)
atom-snowflake-css, v0.1.1 (inactive)
atom-typescript, v10.1.13 (active)
aurora-theme, v1.2.2 (inactive)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-java, v1.2.5 (inactive)
autocomplete-js-import, v1.2.1 (active)
ax-monokai-syntax, v0.1.0 (inactive)
bootstrap-3-snippetset, v0.0.6 (active)
bootstrap3-snippets, v0.1.2 (active)
browser-plus, v0.0.87 (inactive)
browser-refresh, v0.9.0 (active)
busy-signal, v1.2.0 (active)
cdn-libs, v0.1.2 (active)
cdnjs, v1.5.5 (inactive)
color-picker, v2.2.3 (active)
colorblind-wombat-dark-syntax, v0.5.2 (inactive)
colorpicker, v0.3.0 (active)
create-github-repo, v1.1.2 (active)
css-clean, v2.15.0 (inactive)
css-color-underline, v1.0.1 (active)
css-comb, v2.5.0 (active)
css-declaration-sorter, v0.4.0 (inactive)
css-edit-groups, v0.4.2 (inactive)
css-from-html, v0.1.5 (inactive)
css-skeleton-maker, v0.1.4 (inactive)
css-snippets, v1.1.0 (active)
css-specificity, v0.2.2 (active)
css-spy, v0.6.0 (active)
css-to-inline, v1.1.0 (inactive)
css-triggers, v1.0.1 (active)
cssbeautify, v1.3.0 (inactive)
cssfmt, v1.4.0 (inactive)
darkula-ui, v0.1.0 (inactive)
debug, v0.0.1 (active)
debugger, v0.0.1 (active)
dracula-theme, v1.2.8 (inactive)
dracula-ui, v0.3.0 (inactive)
eclipse-keybindings, v0.9.0 (active)
emmet, v2.4.3 (active)
emmet-jsx-css-modules, v1.0.0 (active)
es6-javascript, v1.0.0 (inactive)
eval-javascript, v1.2.0 (inactive)
export-html, v3.0.0 (inactive)
file-icons, v1.7.25 (inactive)
format-javascript-comment, v0.2.2 (active)
formatter-jsbeautify, v1.0.2 (active)
genesis-snippets, v2.1.0 (inactive)
gist-it, v0.9.1 (inactive)
github-issues, v0.7.1 (active)
github-notifications, v0.1.2 (active)
github-plus, v1.0.0 (inactive)
github-search, v0.1.0 (inactive)
github-url-resolver, v0.1.1 (inactive)
github-user-datatip, v0.3.2 (active)
github-utils, v1.6.0 (active)
go-config, v1.2.4 (active)
go-debug, v0.1.22 (active)
go-get, v2.1.1 (active)
gulp-manager, v0.2.19 (active)
Handlebars, v1.7.0 (active)
html-entities, v0.4.0 (active)
html-entitize, v1.1.0 (active)
html-head-snippets, v0.2.0 (active)
html-id-class-snippets, v1.4.1 (active)
html-nested-comments, v3.2.1 (inactive)
html-outliner, v0.1.1 (active)
html-tab, v1.0.2 (inactive)
html-to-css, v0.2.2 (inactive)
html-to-elm, v0.2.0 (inactive)
html-to-javascript, v0.2.0 (inactive)
html-to-string, v0.2.3 (inactive)
HTML2JS, v0.2.1 (inactive)
hydra-syntax-theme, v2.0.4 (inactive)
imdone-atom, v2.0.19 (active)
imdone-atom-github, v0.1.11 (active)
improved-asp-html, v1.8.1 (active)
jade-beautify, v0.1.5 (inactive)
javascript-object-snippets, v0.3.0 (active)
javascript-refactor, v0.5.5 (inactive)
javascript-snippets, v1.2.1 (active)
javascript-standard-snippets, v0.2.1 (active)
jQuery, v1.2.5 (active)
jquery-snippets, v11.0.0 (active)
json-colorer, v0.3.0 (active)
json-schema, v0.1.15 (active)
jsonlint, v1.1.4 (active)
kuali-dark-ui, v1.0.0 (inactive)
language-asp-html, v0.2.0 (active)
language-b-html, v1.0.0 (active)
language-javascript-better, v1.7.1 (active)
language-javascript-jsx, v0.3.7 (active)
language-javascript-subtlegradient, v0.1.0 (active)
language-markdown, v0.18.1 (active)
language-perl-html-template, v1.0.2 (active)
language-riot-tag, v0.2.2 (active)
language-ts, v1.0.2 (active)
language-typescript-grammars-only, v1.5.0 (active)
linter, v1.11.18 (active)
linter-bootlint, v1.0.2 (active)
linter-chktex, v1.3.0 (active)
linter-erb, v1.0.3 (active)
linter-jsonlint, v1.3.0 (active)
linter-manager, v0.2.12 (active)
linter-pep8, v1.3.2 (active)
linter-sass-lint, v1.7.4 (active)
linter-spell-html, v0.6.1 (inactive)
linter-spell-javascript, v0.7.1 (inactive)
linter-tidy, v2.3.0 (active)
linter-tslint, v0.12.0 (active)
livescript-compile, v0.1.1 (active)
livestyle-atom, v0.2.7 (active)
Lucario, v2.0.0 (inactive)
meteor-api, v2.20.0 (active)
metro-syntax, v0.3.1 (inactive)
minimap, v4.26.4 (active)
minimap-bookmarks, v0.4.2 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
minimap-pigments, v0.2.2 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
monokai-dark, v1.3.0 (inactive)
monokai-flat, v1.0.1 (inactive)
monokai-seti, v0.7.0 (inactive)
monokai-slate, v0.6.0 (inactive)
my-github-profile, v0.2.1 (active)
nativescript-ng2-atom-snippets, v1.2.0 (active)
neutron-syntax, v0.7.0 (inactive)
neutron-ui, v0.4.0 (inactive)
ng2-snippets, v0.2.2 (active)
node-debugger, v1.9.1 (active)
nord-atom-syntax, v0.4.0 (active)
nord-atom-ui, v0.9.0 (inactive)
open-github-from-npm, v0.1.1 (active)
open-gitup, v0.0.8 (inactive)
open-html-in-browser, v0.1.0 (inactive)
open-in-browser, v0.4.7 (inactive)
open-in-browsers, v0.0.19 (active)
open-recent, v5.0.0 (active)
pigments, v0.38.0 (active)
polymer-snippets, v3.2.1 (inactive)
precss, v0.3.0 (inactive)
pretty-json, v1.6.1 (active)
project-manager, v3.3.3 (active)
project-plus, v0.9.0 (active)
project-ring, v0.39.0 (active)
project-view, v0.6.1 (active)
project-viewer, v0.3.39 (active)
pull-request, v0.2.1 (inactive)
pull-requests, v0.0.24 (active)
Quick-JavaScript, v2.2.0 (active)
quick-query, v0.8.8 (inactive)
script, v3.12.2 (inactive)
seti-icons, v1.3.4 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
show-repository-web, v0.1.2 (inactive)
solarized-seti-ui, v0.8.6 (active)
titanium-language-javascript, v0.48.0 (inactive)
todo-manager, v0.2.10 (active)
todo-show, v1.8.0 (inactive)
tron-legacy-syntax, v0.5.0 (inactive)
tron-legacy-theme, v0.8.0 (inactive)
tron-legacy-ui, v0.6.0 (inactive)
tron-theme, v0.3.2 (inactive)
turbo-javascript, v1.4.0 (inactive)
typescript-modules-helper, v0.6.2 (active)
v-bootstrap4, v0.1.8 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mda6** [comment]
i just installed it and got this error

**Comment by mchiba52** [comment]
It works if you follow the instructions below:

1. I have problem loading this package?

on your command prompt for atom directory, try uninstalling the package and reinstalling it

apm uninstall browser-plus

apm install browser-plus
if there is package dependency issue(jquery.autocomplete.js no found error messages etc) try

apm rebuild-module-cache

if still issues with jquery.automcomple. delete the jquery-ui directory under node_modules and npm install --> in the browser-plus directory. This will install all dependency

**Comment by skandasoft** [comment]
check the latest patch ....if still issue try  running apm rebuild-module-cache on the atom packages directory
