### ISSUE TITLE
Uncaught Error: Cannot call isDevToolsOpened because the webContents is unavailable. The WebView ...

### ISSUE THREAD

**Issue by LouDog105** [skandasoft/browser-plus#131]
[Enter steps to reproduce below:]

1. Cntl P > Open Current
2. Clicked the wrench and screwdriver. 

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: "Fedora release
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.87

### Stack Trace

Uncaught Error: Cannot call isDevToolsOpened because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:412

Error: Cannot call isDevToolsOpened because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.isDevToolsOpened (/usr/share/atom/resources/electron.asar/renderer/web-view/web-view.js:412:15)
    at BrowserPlusView.module.exports.BrowserPlusView.toggleDevTool (/home/r3lentless/.atom/packages/browser-plus/lib/browser-plus-view.coffee:423:23)
    at HTMLSpanElement.<anonymous> (/home/r3lentless/.atom/packages/browser-plus/lib/browser-plus-view.coffee:242:10)
    at HTMLSpanElement.dispatch (/home/r3lentless/.atom/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/home/r3lentless/.atom/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
 27x -8:05.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -6:18 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:02.3.0 timecop:view (div.panels)
     -2:43 command-palette:toggle (div.package-detail.panels-item)
     -2:41.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:37.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -2:36.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:36.8.0 browser-plus:open (div.package-detail.panels-item)
     -2:13.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -2:11.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:36.3.0 command-palette:toggle (webview.native-key-bindings)
     -1:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:10.8.0 browser-plus:openCurrent (webview.native-key-bindings)
     -0:43.4.0 command-palette:toggle (webview.native-key-bindings)
     -0:40.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:40.8.0 browser-plus:openCurrent (webview.native-key-bindings)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
autoclose-html, v0.23.0 (active)
autocomplete-html-entities, v0.1.0 (active)
browser-plus, v0.0.87 (active)
color-picker, v2.2.3 (active)
file-icons, v1.7.25 (active)
git-plus, v5.29.1 (active)
minimap, v4.25.7 (active)
split-diff, v1.1.0 (active)
trailing-semicolon, v1.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (active)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (active)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by Shamvuchandradas** [comment]
very good.

**Comment by TmasLove** [comment]
Anyway to fix this? I have the same error and I need to get back to studying

**Comment by skandasoft** [comment]
may be document is not yet loaded..is it happening for  all webpages...do you have a way to recreate this.

**Comment by skandasoft** [comment]
check the latest patch...
