### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by iameronmosele** [skandasoft/browser-plus#138]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.87

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At /home/eronmosele-dev/.atom/packages/browser-plus/lib/browser-plus-view.coffee:417

TypeError: Cannot read property 'get' of undefined
    at BrowserPlusView.module.exports.BrowserPlusView.checkFav (/packages/browser-plus/lib/browser-plus-view.coffee:417:30)
    at /packages/browser-plus/lib/browser-plus-view.coffee:154:12)
    at WebViewImpl.dispatchEvent (/opt/atom/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (/opt/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (/opt/atom/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -0:23.3.0 time-notes:enter_pressed (atom-workspace.workspace.scrollbars-visible-always.editor-background.theme-atom-light-syntax.theme-soda-light-ui)
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-styleguide-snippets 0.9.1 
angularjs-styleguide-snippets-es6 1.0.3 
api-docs 0.0.6 
artisan 0.2.0 
ask-stack 2.2.0 
atom-autocomplete-php 0.22.2 
atom-beautify 0.29.17 
atom-bootstrap3 1.2.12 
atom-clock 0.1.6 
atom-commander 0.8.7 
atom-css-comb 3.1.0 
atom-homestead 1.0.1 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-minify 0.8.0 
atom-music 0.7.0 
atom-php-navigation 0.6.0 
atom-react-native-autocomplete 0.0.27 
atom-react-native-css 1.1.3 
atom-react-preview 2.0.0 
atom-ternjs 0.18.2 
atom-vagrant-manager 1.0.4 
atom-wordpress 0.3.0 
atom-yeoman 0.3.15 
atomatigit 1.5.5 
autocomplete-ionic-framework 0.2.2 
autocomplete-ionic2-framework 0.3.2 
autocomplete-wordpress-hooks 0.2.2 
blade-snippets 0.2.0 
blade-spacer 0.4.2 
browser-plus 0.0.87 
cobalt2-syntax 0.5.1 
composer 0.5.0 
css-snippets 1.1.0 
d3-snippets 0.2.0 
data-atom 0.25.0 
diagrams 0.26.4 
docblockr 0.9.1 
editor-background 1.2.38 
emmet 2.4.3 
es6-javascript 1.0.0 
eval-javascript 1.2.0 
fei-light-syntax 0.1.0 
file-type-icons 1.3.3 
fonts 2.0.0 
git-control 0.8.2 
git-plus 7.3.3 
git-time-machine 1.5.6 
gloom 0.4.7 
graphite-ui 0.15.1 
hasklig 0.3.0 
hyperclick 0.0.40 
ionic-framework-snippets 1.2.1 
ionic-preview 0.7.0 
javascript-snippets 1.2.1 
jQuery 1.2.5 
js-hyperclick 1.10.1 
language-blade 0.28.1 
language-diff 0.7.0 
language-javascript-jsx 0.3.7 
language-vue 0.21.2 
language-vue-component 0.5.0 
larasnippets 0.42.0 
laravel 0.7.1 
laravel-eloquent-snippets 2.0.0 
linter 1.11.23 
linter-bootlint 1.0.4 
linter-php 1.3.1 
ng2-snippets 0.2.2 
nord-atom-syntax 0.6.0 
nord-atom-ui 0.10.2 
overwatch-light-syntax 0.4.0 
pdf-view 0.55.0 
php-composer-completion 0.3.4 
php-hyperclick 1.2.1 
php-integrator-autocomplete-plus 1.3.0 
platformio-ide-terminal 2.5.0 
react 0.16.2 
react-es6-snippets 0.3.0 
Remote-FTP 0.10.7 
slack-ui-alter 0.8.3 
soda-light-ui 0.2.0 
theme-switch 0.4.0 
time-notes 0.2.1 
video-player 2.3.0 
videoplayer 1.2.1 
vue-autocomplete 0.1.1 
vue-format 0.4.0 
vue-hyperclick 0.2.0 
vue2-autocomplete 0.1.0-alpha.4 
white-ui 2.6.2 
wordpress-api 1.2.2 
wordpress-dictionary 4.4.0 
wordpress-suite 0.4.5 
wp-dev 0.3.5 
zentabs 0.8.8 
zp-acf-snippets 0.4.0 
```

**Comment by mhnavarro** [comment]
Same issue here.
Is caused by `editor-background`

**Comment by skandasoft** [comment]
taken care with the latest...patch..thought I am not fan of editor-background 👍
