### ISSUE TITLE
Failed to activate the browser-plus package   (My browser-plus of Atom doesn`t work ~!)

### ISSUE THREAD

**Issue by Sophie521** [skandasoft/browser-plus#140]
Failed to activate the browser-plus package
Cannot read property 'get' of undefined
Hide Stack Trace
TypeError: Cannot read property 'get' of undefined
    at Object.module.exports.BrowserPlus.activate (file:///C:/Users/PengZheng/.atom/packages/browser-plus/lib/browser-plus.coffee:38:64)
    at Package.module.exports.Package.activateNow (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:183:20)
    at C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:92:15)
    at C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (C:\Users\PengZheng\AppData\Local\atom\app-1.9.9\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
The error was thrown from the browser-plus package. This issue has already been reported.
View Issue

please tell me how to solove this problem and thank you very much.

**Comment by Pyragon** [comment]
Is this straight after installing?

Can you please try uninstalling browser-plus via your Settings pane and reinstalling?

If the problem persists, ensure there is a 'node_modules' package inside %atom_installation%/packages/browser-plus, if so, also make sure there is a 'jStorage' directory inside, and lemme know :D

**Comment by bsussman** [comment]
Deleter uninstalled/installed.
Snip of console session follows. As you can see, node_modules is there, jStorage is not:
```
[10:59] ~/.atom/packages/browser-plus$ ls -ln
total 6.5M
-rw-r--r--   1 1000 1000  215 May  3 10:36 1.html
-rw-r--r--   1 1000 1000 2.8M May  3 10:36 browser.gif
-rw-r--r--   1 1000 1000  205 May  3 10:36 CHANGELOG.md
drwxr-xr-x   2 1000 1000 4.0K May  3 10:36 keymaps
drwxr-xr-x   2 1000 1000 4.0K May  3 10:36 lib
-rw-r--r--   1 1000 1000 1.1K May  3 10:36 LICENSE.md
drwxr-xr-x   2 1000 1000 4.0K May  3 10:36 menus
drwxr-xr-x 117 1000 1000 4.0K May  3 10:36 node_modules
-rw-r--r--   1 1000 1000   44 May  3 10:36 .npmignore
-rw-r--r--   1 1000 1000  12K May  3 10:36 package.json
-rw-r--r--   1 1000 1000 3.7M May  3 10:36 preview.gif
-rw-r--r--   1 1000 1000 9.1K May  3 10:36 README.md
drwxr-xr-x   3 1000 1000 4.0K May  3 10:36 resources
drwxr-xr-x   2 1000 1000 4.0K May  3 10:36 styles
-rw-r--r--   1 1000 1000   35 May  3 10:36 theme.css
```


```

**Comment by Pyragon** [comment]
@bsussman I should have been more specific sorry, jStorage should be inside node_modules.

**Comment by bsussman** [comment]
Ah - ok it is there but not with a capital 'S':

I don't know whether your code cares about directory capitalization.
```
[18:38] ~/.atom/packages/browser-plus/node_modules$ ls -l|grep orag
drwxr-xr-x  5 1000 1000 4.0K May  3 10:36 jstorage
[18:38] ~/.atom/packages/browser-plus/node_modules$ 
```

**Comment by hechengyuan** [comment]
My Mac also appear in this situation.

**Comment by Pyragon** [comment]
Can you tell me what OS you are using, what version of Atom you have?

**Comment by Rundik** [comment]
I have that problem too

**Comment by ipapu** [comment]
same problem

**Comment by malix213** [comment]
Same problem in windows 7 x64

**Comment by rittou** [comment]
how to solve it ?

**Comment by skandasoft** [comment]
check the latest patch..if still issues..go to the atom package directory and try 
```
apm rebuild-module-cache
```

**Comment by bsussman** [comment]
Cool - works for me now :)

**Comment by HelloFish-2016** [comment]
I have same problem，how to solve it

**Comment by HelloFish-2016** [comment]
TypeError: Cannot read property 'jStorage' of undefined
    at Object.activate (file:///C:/Users/Mangoer/.atom/packages/browser-plus/lib/browser-plus.coffee:41:41)
    at Package.module.exports.Package.activateNow (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package.js:253:25)
    at C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package.js:225:38
    at Package.module.exports.Package.measure (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package.js:99:21)
    at C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package.js:218:32
    at Package.module.exports.Package.activate (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package.js:215:40)
    at PackageManager.activatePackage (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\package-manager.js:690:42)
    at C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\node_modules\settings-view\lib\package-manager.js:535:35
    at exit (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\Mangoer\AppData\Local\atom\app-1.21.2\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
The error was thrown from the browser-plus package. This issue has already been reported.
