### ISSUE TITLE
webContents unavailable

### ISSUE THREAD

**Issue by TmasLove** [skandasoft/browser-plus#148]
[Enter steps to reproduce:]

1. click live icon 
2. than wrench tool 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.87

### Stack Trace

Uncaught Error: Cannot call isDevToolsOpened because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412

Error: Cannot call isDevToolsOpened because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.isDevToolsOpened (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412:15)
    at BrowserPlusView.module.exports.BrowserPlusView.toggleDevTool (/packages/browser-plus/lib/browser-plus-view.coffee:423:23)
    at /packages/browser-plus/lib/browser-plus-view.coffee:242:10)
    at HTMLSpanElement.dispatch (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -7:32.7.0 tree-view:remove (div.header.list-item)
     -6:35.7.0 core:select-all (input.hidden-input)
     -6:28.9.0 browser-plus:open (div.line)
     -4:22.7.0 core:select-all (input.hidden-input)
     -4:18.7.0 browser-plus:open (div.line)
     -4:07.6.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:02.6.0 open-on-github:copy-url (input.hidden-input)
     -0:07.5.0 browser-plus:open (div.line)
```

### Non-Core Packages

```
browser-plus 0.0.87 
emmet 2.4.3 
minimap 4.28.1 
package-list 0.1.2 
```

**Comment by TmasLove** [comment]
bump. any updates?

**Comment by skandasoft** [comment]
Going to track it from other issue...https://github.com/skandasoft/browser-plus/issues/131..
Also can you update on how to recreate it ..I tried recreating ..could not(switching on live + dev tool switched on )
