### ISSUE TITLE
Uncaught TypeError: Cannot set property 'http://127.0.0.1:8000/source/index.html' of null

### ISSUE THREAD

**Issue by eisho** [skandasoft/browser-plus#151]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'http://127.0.0.1:8000/source/index.html' of null

```
At /Users/eisho/.atom/packages/browser-plus/lib/browser-plus-view.coffee:241

TypeError: Cannot set property 'http://127.0.0.1:8000/source/index.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -1:51.9.0 application:open (input.hidden-input)
  2x -1:46.2.0 sphinx-preview:toggle (input.hidden-input)
     -0:37.1.0 link:open (input.hidden-input)
     -0:29.6.0 sphinx-preview:toggle (a.inline-block)
```

### Non-Core Packages

```
browser-plus 0.0.91 
language-restructuredtext 1.1.0 
sphinx-preview 0.1.1 
vim-mode-plus 0.93.0 
```

**Comment by skandasoft** [comment]
fixed with latest patch
