### ISSUE TITLE
Uncaught TypeError: Cannot set property 'file://~/Documents/Course%20Folder/index.html' of null

### ISSUE THREAD

**Issue by vovka89** [skandasoft/browser-plus#152]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'file:///Users/vladimir/Documents/Course%20Folder/index.html' of null

```
At /Users/vladimir/.atom/packages/browser-plus/lib/browser-plus-view.coffee:241

TypeError: Cannot set property 'file:///Users/vladimir/Documents/Course%20Folder/index.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -7:38.9.0 core:paste (input.hidden-input)
     -7:12.4.0 core:save-as (input.hidden-input)
  2x -5:09.0 core:backspace (input.hidden-input)
     -4:59.9.0 core:select-all (input.hidden-input)
  6x -4:59 core:backspace (input.hidden-input)
  3x -4:45.4.0 core:confirm (input.hidden-input)
     -0:26.5.0 command-palette:toggle (input.hidden-input)
     -0:12.8.0 browser-plus:open (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.91 
```

**Comment by skandasoft** [comment]
fixed with latest patch
