### ISSUE TITLE
Uncaught TypeError: Cannot set property 'file:///C:/Users/user/Desktop/js/index.html' of null

### ISSUE THREAD

**Issue by VladivirYa** [skandasoft/browser-plus#153]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'file:///C:/Users/user/Desktop/js/index.html' of null

```
At C:\Users\user\.atom\packages\browser-plus\lib\browser-plus-view.coffee:241

TypeError: Cannot set property 'file:///C:/Users/user/Desktop/js/index.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -9:26.6.0 core:save (input.hidden-input)
     -6:38.5.0 core:backspace (input.hidden-input)
     -6:37.4.0 core:confirm (input.hidden-input)
     -5:29.1.0 core:backspace (input.hidden-input)
     -5:28.8.0 core:confirm (input.hidden-input)
  2x -3:54.6.0 core:backspace (input.hidden-input)
     -3:47.6.0 core:confirm (input.hidden-input)
     -1:14.1.0 browser-plus:open (div.line)
  3x -0:51.6.0 core:backspace (input.hidden-input)
  2x -0:50.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-bootstrap4 1.4.0 
atom-jade 0.3.0 
browser-plus 0.0.91 
color-picker 2.2.5 
emmet 2.4.3 
git-plus 7.9.3 
gulp-control 0.5.0 
minimap 4.28.2 
monokai 0.24.0 
seti-ui 1.8.0 
```

**Comment by skandasoft** [comment]
fixed with latest patch
