### ISSUE TITLE
Uncaught TypeError: Cannot set property 'file://~/Desktop/Works%20in%20Progress/test.html' of null

### ISSUE THREAD

**Issue by Pendemonium** [skandasoft/browser-plus#154]
[Enter steps to reproduce:]

1. Had a local test HTML file open in Atom
2. option-control-O triggered the error

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'file:///Users/collin/Desktop/Works%20in%20Progress/test.html' of null

```
At /Users/collin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:241

TypeError: Cannot set property 'file:///Users/collin/Desktop/Works%20in%20Progress/test.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -1:03.3.0 tree-view:toggle (div.panels-item)
     -0:30.8.0 link:open (input.hidden-input)
     -0:23.8.0 browser-plus:open (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-wrap-in-tag 0.6.0 
autoclose-html 0.23.0 
browser-plus 0.0.91 
double-tag 0.8.0 
markdown-preview-plus 2.4.9 
tag 0.5.0 
wrap-with-anything 0.1.1 
```

**Comment by skandasoft** [comment]
fixed with latest patch
