### ISSUE TITLE
Uncaught TypeError: Cannot set property "file_path/index.html" of null

### ISSUE THREAD

**Issue by singh-dinesh** [skandasoft/browser-plus#155]
Tried to install with both gui and cli but still getting the same error .`npm install ` in the .atom/packages/browser-install doesn't solved anything.This error is occurring whenever I open the browser.

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'file:///C:/Users/dines/Desktop/UDA/Front/fend-animal-trading-cards-master/card.html' of null

```
At C:\Users\dines\.atom\packages\browser-plus\lib\browser-plus-view.coffee:241

TypeError: Cannot set property 'file:///C:/Users/dines/Desktop/UDA/Front/fend-animal-trading-cards-master/card.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at dispatchEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/electron.asar/renderer/web-view/guest-view-internal.js:55:11)
    at dispatchEvent (~/AppData/Local/atom/app-1.19.0-beta0/resources/electron.asar/renderer/web-view/guest-view-internal.js:49:71)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.19.0-beta0/resources/electron.asar/renderer/web-view/guest-view-internal.js:72:55)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
  3x -0:54.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.0.4 
browser-plus 0.0.91 
emmet 2.4.3 
native-ui 0.21.0 
pristine-ui 1.0.15 
unity-ui 2.1.11 
```

**Comment by skandasoft** [comment]
fixed with latest patch
