### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jStorage' of undefined

### ISSUE THREAD

**Issue by coleer** [skandasoft/browser-plus#156]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot read property 'jStorage' of undefined

```
At C:\Users\evion\.atom\packages\browser-plus\lib\browser-plus-view.coffee:237

TypeError: Cannot read property 'jStorage' of undefined
    at /packages/browser-plus/lib/browser-plus-view.coffee:237:24)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -8:16.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
atom-code-music 2.3.3 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-mocha 0.0.12 
atom-runner 2.7.1 
browser-plus 0.0.91 
browser-plus-open-new-window 0.0.1 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
clipboard-history 0.6.6 
color-picker 2.2.5 
docblockr 0.10.3 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.7 
flex-tool-bar 0.12.0 
git-control 0.9.0 
git-plus 7.9.3 
imdone-atom 2.2.6 
language-babel 2.66.0 
linter 2.1.4 
linter-eslint 8.2.1 
linter-stylelint 3.10.0 
linter-ui-default 1.6.1 
local-history 4.3.0 
markdown-writer 2.6.5 
merge-conflicts 1.4.5 
minimap 4.28.2 
mocha-ui 0.1.8 
multi-cursor-plus 1.2.0 
navigate 0.1.17 
node-debugger 1.10.1 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
open-in-browsers 0.0.30 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
regex-railroad-diagram 0.17.0 
todo-show 1.11.0 
tool-bar 1.1.0 
tree-view-git-status 1.4.0 
```

**Comment by coleer** [comment]
thank you.I installed the update and everything is working well again
