### ISSUE TITLE
Uncaught TypeError: Cannot set property 'file:///C:/Users/Rali/Desktop/JScript/index.html' of null

### ISSUE THREAD

**Issue by rali1974** [skandasoft/browser-plus#158]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91

### Stack Trace

Uncaught TypeError: Cannot set property 'file:///C:/Users/Rali/Desktop/JScript/index.html' of null

```
At C:\Users\Rali\.atom\packages\browser-plus\lib\browser-plus-view.coffee:241

TypeError: Cannot set property 'file:///C:/Users/Rali/Desktop/JScript/index.html' of null
    at /packages/browser-plus/lib/browser-plus-view.coffee:241:9)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:49:5)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
```

### Commands

```
     -5:23.9.0 core:move-down (input.hidden-input)
     -5:23.6.0 core:move-up (input.hidden-input)
     -5:22.9.0 autocomplete-plus:confirm (input.hidden-input)
     -5:20.6.0 editor:newline (input.hidden-input)
     -5:18 core:save (input.hidden-input)
     -3:38.2.0 tree-view:reveal-active-file (div.line)
  5x -3:11.2.0 core:undo (input.hidden-input)
  2x -3:05.6.0 core:move-right (input.hidden-input)
     -3:03.6.0 core:move-up (input.hidden-input)
     -3:01.0 core:move-left (input.hidden-input)
 17x -2:55.4.0 core:move-right (input.hidden-input)
     -2:50 editor:newline (input.hidden-input)
     -2:48.5.0 core:save (input.hidden-input)
  3x -2:36.7.0 core:delete (input.hidden-input)
     -2:33.7.0 core:backspace (input.hidden-input)
     -2:29.9.0 core:delete (input.hidden-input)
```

### Non-Core Packages

```
atom-live-server 2.1.2 
browser-plus 0.0.91 
```

**Comment by skandasoft** [comment]
fixed with latest patch
