### ISSUE TITLE
Uncaught Error: Cannot call reload because the webContents is unavailable. The WebView must be at...

### ISSUE THREAD

**Issue by medskill** [skandasoft/browser-plus#160]
Error caused by refreshing a new tab (browser-plus://blank -> refresh btn) 

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.97

### Stack Trace

Uncaught Error: Cannot call reload because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /private/var/folders/8n/pm5172b57dd5lb3c53slb4lc0000gp/T/AppTranslocation/2A8EEA26-8916-4A41-89C8-E739B91BD839/d/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412

Error: Cannot call reload because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.reload (/private/var/folders/8n/pm5172b57dd5lb3c53slb4lc0000gp/T/AppTranslocation/2A8EEA26-8916-4A41-89C8-E739B91BD839/d/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412:15)
    at BrowserPlusView.module.exports.BrowserPlusView.refreshPage (/packages/browser-plus/lib/browser-plus-view.coffee:412:24)
    at /packages/browser-plus/lib/browser-plus-view.coffee:360:10)
    at HTMLSpanElement.dispatch (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -4:33.3.0 autocomplete-plus:confirm (input.hidden-input)
     -4:32.5.0 editor:select-to-first-character-of-line (input.hidden-input)
     -4:32.4.0 core:backspace (input.hidden-input)
     -4:31.8.0 core:save (input.hidden-input)
  2x -4:17.7.0 core:paste (input#url.native-key-bindings)
     -4:12.2.0 core:select-all (input#url.native-key-bindings)
     -4:12 core:paste (input#url.native-key-bindings)
     -4:09.6.0 core:select-all (input#url.native-key-bindings)
  2x -4:09.0 core:paste (input#url.native-key-bindings)
     -4:00.1.0 core:undo (input#url.native-key-bindings)
     -3:53.2.0 core:paste (input.hidden-input)
     -3:52.3.0 core:undo (input.hidden-input)
     -3:51.7.0 core:paste (input#url.native-key-bindings)
     -3:50.9.0 core:cancel (input#url.native-key-bindings)
     -3:50.1.0 core:undo (input#url.native-key-bindings)
     -3:17.9.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-bootstrap3 1.2.12 
atom-html-preview 0.1.22 
browser-plus 0.0.97 
pp 0.0.1 
```

**Comment by sloanstewart** [comment]
I solved this by installing this package: [https://atom.io/packages/web-view](https://atom.io/packages/web-view)
