### ISSUE TITLE
Uncaught TypeError: window.bp.js.get is not a function

### ISSUE THREAD

**Issue by angel1027** [skandasoft/browser-plus#163]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98

### Stack Trace

Uncaught TypeError: window.bp.js.get is not a function

```
At C:\Users\Administrator\.atom\packages\browser-plus\lib\browser-plus-view.coffee:481

TypeError: window.bp.js.get is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.checkFav (/packages/browser-plus/lib/browser-plus-view.coffee:481:26)
    at BrowserPlusView.module.exports.BrowserPlusView.updatePageUrl (/packages/browser-plus/lib/browser-plus-view.coffee:387:8)
    at /packages/browser-plus/lib/browser-plus-view.coffee:228:10)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/web-view.js:192:29)
    at dispatchEvent (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:57:11)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/renderer/web-view/guest-view-internal.js:66:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -3:43.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-css-comb 3.2.0 
atom-html-preview 0.1.22 
atom-terminal-panel 4.4.4 
autocomplete-bibtex 0.7.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
autoprefixer 3.7.1 
browser-plus 0.0.98 
color-picker 2.2.5 
docblockr 0.10.5 
emmet 2.4.3 
file-icons 2.1.8 
git-plus 7.9.3 
less-autocompile 1.0.0 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-jshint 3.1.5 
linter-php 1.3.2 
minimap 4.28.3 
project-manager 3.3.5 
tree-view-finder 0.2.1 
```

**Comment by HOHOOO** [comment]
I have the same problem when the jupyter notebook was opened in  the ATOM. 

**Atom**: 1.19.3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98


### Stack Trace

Uncaught TypeError: window.bp.js.get is not a function

```
At /Users/houzhiwei/.atom/packages/browser-plus/lib/browser-plus-view.coffee:481

TypeError: window.bp.js.get is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.checkFav (/packages/browser-plus/lib/browser-plus-view.coffee:481:26)
    at BrowserPlusView.module.exports.BrowserPlusView.updatePageUrl (/packages/browser-plus/lib/browser-plus-view.coffee:387:8)
    at /packages/browser-plus/lib/browser-plus-view.coffee:228:10)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:55:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/guest-view-internal.js:72:55)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:31.3.0 markdown-preview-plus:toggle (input.hidden-input)
     -4:28.1.0 link:open (input.hidden-input)
     -3:29.9.0 core:confirm (input.hidden-input)
     -3:20.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -3:20.7.0 docblockr:parse-enter (input.hidden-input)
     -3:20.7.0 editor:newline (input.hidden-input)
     -3:10.7.0 core:move-left (input.hidden-input)
     -3:10.3.0 core:move-right (input.hidden-input)
     -3:05.1.0 core:save (input.hidden-input)
     -2:55.5.0 browser-plus:open (input.hidden-input)
     -2:37.1.0 core:close (atom-pane.pane.active)
     -2:30.1.0 browser-plus:open (div.package-detail.panels-item)
  2x -2:27.1.0 core:paste (input#url.native-key-bindings)
  2x -1:25.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-beautify 0.30.5 
atom-clock 0.1.13 
atom-translator 0.2.1 
atom-zh-dictionary 0.4.4 
autocomplete-python 1.10.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
colorblind-wombat-dark-syntax 0.6.0 
docblockr 0.11.0 
editor-background 1.2.41 
expose 0.14.0 
figlet 0.5.4 
file-icons 2.1.11 
floobits 0.32.11 
git-plus 7.9.3 
hey-pane 1.0.0 
Hydrogen 1.20.0 
hydrogen-launcher 1.2.1 
imdone-atom 2.2.6 
imdone-atom-github 0.1.11 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.7 
markdown-img-paste 0.3.9 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-writer 2.6.5 
minimap 4.29.6 
minimap-find-and-replace 4.5.2 
move-panes 0.2.0 
open-in-github-app 0.2.6 
project-manager 3.3.5 
script 3.15.0 
simplified-chinese-menu 5.3.4 
sync-settings 0.8.2 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
video-player 2.4.0 
```

**Comment by dov-yih** [comment]
I don't know why. before I reinstall this package it works well. One day I found it doesn't work because of this issues, so I try to reinstall it, but it seen doesn't work.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0-beta1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98


### Stack Trace

Uncaught TypeError: window.bp.js.get is not a function

```
At C:\Users\yidafu\.atom\packages\browser-plus\lib\browser-plus-view.coffee:197

TypeError: window.bp.js.get is not a function
    at /packages/browser-plus/lib/browser-plus-view.coffee:197:29)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.22.0-beta1/resources/electron.asar/renderer/web-view/web-view.js:175:22)
    at dispatchEvent (~/AppData/Local/atom/app-1.22.0-beta1/resources/electron.asar/renderer/web-view/guest-view-internal.js:55:11)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.22.0-beta1/resources/electron.asar/renderer/web-view/guest-view-internal.js:72:55)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:58.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.editor-background)
     -1:45.8.0 window:toggle-dev-tools (div.panels-item)
     -1:13.3.0 command-palette:toggle (atom-pane.pane)
     -1:06.9.0 core:move-down (input.hidden-input)
     -1:06.3.0 core:confirm (input.hidden-input)
     -1:06.3.0 browser-plus:open (atom-pane.pane)
```

### Non-Core Packages

```
activate-power-mode 2.5.0 
acute-syntax 1.0.0 
apex-syntax 0.2.0 
apex-ui 1.0.1 
atom-beautify 0.30.5 
atom-clock 0.1.15 
atom-html-preview 0.2.2 
atom-ide-ui 0.5.1 
atom-material-ui 2.0.6 
auto-encoding 0.7.0 
bliss-ui 0.6.0 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.2.5 
convert-file-encoding 0.1.0 
convert-to-utf8 0.2.4 
debug 0.0.1 
docblockr 0.11.0 
editor-background 1.2.41 
emmet 2.4.3 
file-icons 2.1.13 
flex-tool-bar 0.12.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-time-machine 1.5.9 
google-translate-modal 1.2.2 
ide-clangd 0.1.2 
ide-cpp 0.0.2 
ide-css 0.2.0 
ide-html 0.3.0 
ide-java 0.6.5 
ide-php 0.6.9 
ide-typescript 0.6.2 
intentions 1.1.5 
language-markdown 0.25.1 
latex 0.48.0 
linter 2.2.0 
linter-markdown 5.2.0 
linter-ui-default 1.6.10 
loved-syntax 1.0.2 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
min-ui 0.0.4 
minimap 4.29.7 
now-syntax 0.2.4 
open-in-browsers 0.0.30 
pdf-view 0.59.0 
piatto-light-syntax 0.2.2 
polaris-syntax 0.1.0 
pristine-ui 1.1.10 
pure-syntax 0.3.0 
simple-drag-drop-text 0.3.6 
sound 0.6.1 
sync-settings 0.8.3 
tool-bar 1.1.0 
tool-bar-main 0.0.10 
tool-bar-markdown-writer 0.3.0 
trans-en-zh 0.2.5 
vim-mode 0.66.0 
```

**Comment by SwineBurglar** [comment]
We're you able to find a solution for this problem? I'm having the same issue. There are several iterations of this bug report open but I can't find any with a solution.
