### ISSUE TITLE
Uncaught Error: Cannot call reload because the webContents is unavailable. The WebView must be at...

### ISSUE THREAD

**Issue by Kaffarin** [skandasoft/browser-plus#164]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98

### Stack Trace

Uncaught Error: Cannot call reload because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

```
At /private/var/folders/td/stj2lhpd2m34yqll1b5h37nh0000gn/T/AppTranslocation/D32D3981-6F9D-4CC0-A5B7-9CDF716027FD/d/Atom 2.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412

Error: Cannot call reload because the webContents is unavailable. The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at webview.reload (/private/var/folders/td/stj2lhpd2m34yqll1b5h37nh0000gn/T/AppTranslocation/D32D3981-6F9D-4CC0-A5B7-9CDF716027FD/d/Atom 2.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:412:15)
    at BrowserPlusView.module.exports.BrowserPlusView.refreshPage (/packages/browser-plus/lib/browser-plus-view.coffee:412:24)
    at /packages/browser-plus/lib/browser-plus-view.coffee:273:12)
    at HTMLSpanElement.dispatch (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:56.9.0 core:confirm (input.hidden-input)
     -4:20.4.0 spell-check:correct-misspelling (div.line)
     -4:17.3.0 open-in-browser:open (div.line)
     -3:07.2.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-detail.has-close)
  2x -2:29.4.0 core:confirm (input.hidden-input)
     -0:26.9.0 browser-plus:open (div.line)
```

### Non-Core Packages

```
browser-plus 0.0.98 
open-in-browser 0.5.2 
```

**Comment by StudiosSean** [comment]
I also have this problem, I also would like to know what I am doing wrong :/

**Comment by Sel023** [comment]
Did someone ever resolve this?

**Comment by elemenope** [comment]
I managed to resolve mine, but it was because I had a bad script. Check the validity of your HTML/JS.
