### ISSUE TITLE
Uncaught TypeError: window.bp.js.get is not a function

### ISSUE THREAD

**Issue by SpyManxD** [skandasoft/browser-plus#191]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98

### Stack Trace

Uncaught TypeError: window.bp.js.get is not a function

```
At C:\Users\semih\.atom\packages\browser-plus\lib\browser-plus-view.coffee:233

TypeError: window.bp.js.get is not a function
    at /packages/browser-plus/lib/browser-plus-view.coffee:233:29)
    at WebViewImpl.dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/web-view.js:142:22)
    at dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:56:11)
    at dispatchEvent (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:50:5)
    at EventEmitter.<anonymous> (~/AppData/Local/atom/app-1.40.1/resources/electron.asar/renderer/web-view/guest-view-internal.js:74:7)
    at EventEmitter.emit (events.js:182:13)
```

### Commands

```
  2x -3:14.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-atom-dark-ui)
  3x -3:11.5.0 pane:close (div.deprecation-info.list-item)
     -3:03.0 Code-Time:dashboard (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-light-syntax.theme-atom-dark-ui)
     -1:33.6.0 command-palette:toggle (atom-pane.pane.active)
  3x -1:28.9.0 core:backspace (input.hidden-input)
     -0:43.5.0 core:move-down (input.hidden-input)
     -0:41.3.0 core:confirm (input.hidden-input)
     -0:41.3.0 browser-plus:open (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-code 0.3.0 
atom-codeigniter4 0.1.1 
atom-import-cost 1.2.0 
atom-import-sort 6.0.0 
atom-java-decompiler 0.1.2 
atom-javascript-console-snippets 0.10.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-maven 1.3.2 
atom-turkish-files 0.5.0 
atom-webextensions 0.1.1 
atom-webppl-preview 0.3.1 
autocomplete-css-with-stylus-support 1.0.0 
autocomplete-java 1.2.7 
autocomplete-semantic-web 0.0.11 
bad-code 0.3.0 
browser-plus 0.0.98 
browser-refresh-on-save 1.0.0 
bug-report 0.7.1 
build-processing 0.1.2 
busy 0.7.0 
busy-signal 2.0.1 
code-note 0.3.0 
code-peek 1.4.21 
code-swap 2.0.0 
code-time 0.9.1 
codeigniter 0.4.0 
codeigniter-nucleus 0.4.3 
codeigniter3-snippets 1.1.3 
exec-in-cmd 2.2.1 
file-browser 0.4.1 
file-icons 2.1.35 
file-type-icons 1.3.4 
formatter-clangformat 1.0.1 
g-code 1.1.0 
git-support-ide 6.0.1 
google-java-format 0.0.4 
hey-pane 1.2.0 
html-to-javascript 0.2.0 
Hydrogen 2.12.0 
ide-java 0.9.0 
import 1.7.0 
import-export 0.2.1 
intentions 1.1.5 
ionide-webview 1.0.3 
java-class-complete 0.0.6 
java-classpath-registry 0.4.0 
java-generator 2.2.3 
java-import-wiz 0.5.0 
java-importer 1.4.1 
java-plus 0.1.0 
joe-keybinds 1.0.0 
jumpy 5.0.2 
language-autohotkey2 1.0.1 
language-awk 0.1.12 
language-cgx 1.10.0 
language-cup 1.1.2 
language-dlv 0.5.1 
language-e 1.2.0 
language-eu4 0.1.1 
language-gdb 0.7.0 
language-gherkin-i18n 1.3.4 
language-hcl 0.4.0 
language-icon 0.1.1 
language-jcm 0.4.0 
language-msg 0.2.0 
language-nit 1.1.0 
language-ohm 1.0.1 
language-rid 0.3.3 
language-tjs 0.6.2 
language-trf 0.7.0 
language-vex 0.1.3 
language-xst 0.5.0 
linter 2.3.1 
linter-javac 1.10.0 
linter-processing-java 0.1.6 
linter-ui-default 1.8.0 
ll-php-support 0.1.3 
my-package 0.0.0 
nc-gcode 0.2.0 
open-dir-in-iterm 0.2.0 
open-file-in 1.2.3 
open-in-app 0.2.0 
open-in-ia-writer 0.0.1 
open-path 0.3.6 
open-unsupported-files 1.0.20 
portal 0.4.1 
project-manager 3.3.7 
quantum-shell 0.7.1 
rails-open-minitest 0.0.1 
rails-transporter 1.7.1 
run-in-iterm 0.0.2 
sass-code-kit 1.2.0 
script 3.18.1 
scroll-through-time 0.3.1 
send-code 0.4.1 
sml-language-support 0.2.0 
starbound-open-unsupported-files 1.0.2 
support-gbk 2.1.1 
teletype 0.13.4 
turbo-javascript 1.4.0 
unleash-django 1.3.2 
variational-java 0.7.5 
web-accessibility-checker 0.1.4 
web-tools 0.33.0 
zentabs 0.8.9 
```

**Comment by SwineBurglar** [comment]
We're you able to find a solution for this problem? I'm having the same issue. There are several iterations of this bug report open but I can't find any with a solution.
