### ISSUE TITLE
Uncaught TypeError: ref5.reload is not a function

### ISSUE THREAD

**Issue by DalekZED** [skandasoft/browser-plus#195]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98

### Stack Trace

Uncaught TypeError: ref5.reload is not a function

```
At C:\Users\depie\.atom\packages\browser-plus\lib\browser-plus-view.coffee:412

TypeError: ref5.reload is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.refreshPage (/packages/browser-plus/lib/browser-plus-view.coffee:412:24)
    at /packages/browser-plus/lib/browser-plus-view.coffee:273:12)
    at HTMLSpanElement.dispatch (/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/pp/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:21.3.0 browser-plus:open (input.hidden-input)
  2x -3:16.1.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
browser-plus 0.0.98 
pp 0.0.1 
```

**Comment by icecream17** [comment]
[Enter steps to reproduce:]
[Alt-Ctrl-O but the page didn't show. So I pressed reload and boom, the error.]
[Not actual steps, just what happened.]

*Kinda different*: OS, Stack Trace at HTMLSpanElement.dispatch
*What's different*: Commands, Non-Core Packages

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98


### Stack Trace

Uncaught TypeError: ref5.reload is not a function

```
At C:\Users\[name redacted]\.atom\packages\browser-plus\lib\browser-plus-view.coffee:412

TypeError: ref5.reload is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.refreshPage (/packages/browser-plus/lib/browser-plus-view.coffee:412:24)
    at /packages/browser-plus/lib/browser-plus-view.coffee:360:10)
    at HTMLSpanElement.dispatch (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/atom-html-preview/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:02.7.0 atom-html-preview:toggle (div.line)
     -2:46.7.0 browser-plus:open (div.line)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-html-preview 0.2.6 
atom-js-console 1.2.2 
atom-jshint undefined 
browser-plus 0.0.98 
my-theme-syntax 0.0.0 
pigments 0.40.2 
```

I got this error too - and this is probably not the way to do this.
[Background: Trying to debug... see line 284 if you want.]
[Bad code: https://github.com/icecream17/Stuff/blob/master/adventure.html]
[Whitespace fixed: https://github.com/icecream17/Stuff/blob/master/adventureFormatted.html]

image
![Annotation 2020-05-24 113012](https://user-images.githubusercontent.com/58114641/82759272-f1d10100-9db1-11ea-964f-67e458479e80.png)

**Comment by DalekZED** [comment]
@icecream17 Thanks for the suggestions, first time starting a thread on GH. Also can you elaborate on the "This is probably not the way to do this" comment?
Do you mean something I am doing, the code for the add-on, or just that God meant for us to run all visual checks of a website through an actual browser? Haha

**Comment by icecream17** [comment]
@DalekZED
No, this is my first time too. That's what I meant - I feel like i'm missing something.

Did I suggest anything? I didn't notice...
