### ISSUE TITLE
Uncaught TypeError: ref5.reload is not a function

### ISSUE THREAD

**Issue by liuweihai** [skandasoft/browser-plus#201]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.2
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.98

### Stack Trace

Uncaught TypeError: ref5.reload is not a function

```
At /Users/ganggang/.atom/packages/browser-plus/lib/browser-plus-view.coffee:412

TypeError: ref5.reload is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.refreshPage (/packages/browser-plus/lib/browser-plus-view.coffee:412:24)
    at /packages/browser-plus/lib/browser-plus-view.coffee:360:10)
    at HTMLSpanElement.dispatch (/packages/atom-sync/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/packages/atom-sync/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -1:54.4.0 browser-plus:open (span.syntax--source.syntax--coffee)
  3x -1:44.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:08.7.0 browser-plus:open (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.6 
atom-shell-commands 1.5.0 
browser-plus 0.0.98 
build-npm-apm 0.12.0 
markdown-preview-plus 3.11.5 
minimap 4.29.9 
simplified-chinese-menu 5.3.5 
```

**Comment by jcfor1** [comment]
Hi, I am a website learner and I use Atom. The browser-plus does not open and the warning "Uncaught TypeError: ref5.reload is not a function # 201" appears. What should I do to fix it? Please step by step.
Thanks for your attention.
Johnson

**Comment by icecream17** [comment]
Wow, this looks very similar to issue https://github.com/skandasoft/browser-plus/issues/195
(and maybe issue https://github.com/skandasoft/browser-plus/issues/202 but that one has an underscore in front for some reason)
