### ISSUE TITLE
Failed to load the browser-plus package

### ISSUE THREAD

**Issue by bu2** [skandasoft/browser-plus#30]
[Enter steps to reproduce below:]

1. Download last Atom from Github and build
2. Install 'browser-plus'
3. Launch Atom

Browser-plus failed to load because of following error (top right red box) :

```
Cannot find module 'theorist'
Hide Stack Trace
Error: Cannot find module 'theorist'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/bu2/.atom/packages/browser-plus/lib/browser-plus-model.coffee:2:11)
    at Object.<anonymous> (/Users/bu2/.atom/packages/browser-plus/lib/browser-plus-model.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

When looking at `$ git log`, theorist seems to be deprecated and remove from Atom dependencies since v1.0.

**Atom Version**: 1.0.10-ecd9b22
**System**: Mac OS X 10.10.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.34

### Stack Trace

Failed to load the browser-plus package

```
At Cannot find module 'theorist'

Error: Cannot find module 'theorist'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/bu2/.atom/packages/browser-plus/lib/browser-plus-model.coffee:2:11)
    at Object.<anonymous> (/Users/bu2/.atom/packages/browser-plus/lib/browser-plus-model.coffee:1:1)
    at Module._compile (module.js:452:26)
    at Object.defineProperty.value [as .coffee] (/Users/bu2/lab/atom/myatom/bin/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:347:32)
```

### Commands

```
$ clear && bin/Atom.app/Contents/MacOS/Atom --executed-from="$(pwd)" --pid=$$ --dev
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
autocomplete-ruby, v0.1.0
coffee-compile, v0.18.0
file-icons, v1.6.9
imdone-atom, vundefined
language-haml, v0.21.0
linter, v1.5.0
linter-coffeelint, v1.0.2
linter-ruby, v1.0.2
minimap, v4.13.2
node-debugger, v1.1.8

# Dev
atom-space-pen-views, v2.1.0
browser-plus, v0.0.34
coffee-navigator, v0.1.0
language-ada, v1.1.0
space-pen, v5.1.1
tree-view, v0.186.0
```

**Comment by bu2** [comment]
False alarm.

I install browser-plus as a development package:

- git clone ...
- apm link --dev ...

and failed to install dependencies...

Now it works.

Sorry, you can close this issue.

**Comment by sdaitzman** [comment]
I'm getting this same error, but I installed it from directly within Atom.

**Comment by skandasoft** [comment]
should work now.

**Comment by sdaitzman** [comment]
Thank you :+1:
