### ISSUE TITLE
Last update broke something

### ISSUE THREAD

**Issue by AMPBEdu** [skandasoft/browser-plus#38]
Updated to version 37, and it stopped working.

Step 1: Install browser-plus or run it

Got this error:

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.37

### Stack Trace

Failed to load the browser-plus package

```
At Cannot find module './eval'

Error: Cannot find module './eval'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/gratin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:3:12)
  at Object.<anonymous> (/home/gratin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/home/gratin/.atom/packages/browser-plus/lib/browser-plus.coffee:3:19)
  at Object.<anonymous> (/home/gratin/.atom/packages/browser-plus/lib/browser-plus.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at /usr/share/atom/resources/app.asar/src/package.js:192:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:485:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
  2x -1:40.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.37
color-picker, v2.0.13
highlight-line, v0.11.0
language-html5-subtlegradient, v0.1.0

# Dev
No dev packages
```

**Comment by ovidius72** [comment]
same here

**Comment by skandasoft** [comment]
just fixed it..

**Comment by AMPBEdu** [comment]
Thanks, I really appreciate it :)
