### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by jekriske** [skandasoft/browser-plus#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.15

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/jeff/.atom/packages/browser-plus/lib/browser-plus.coffee:31

ReferenceError: path is not defined
  at /Users/jeff/.atom/packages/browser-plus/lib/browser-plus.coffee:31:12
  at wrappedOpener (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:366:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:47:25)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.15
preview-plus, v1.1.34

# Dev
No dev packages
```

Clean atom install, installed preview-plus and browser-plus... tried to open simple HTML file.

**Comment by skandasoft** [comment]
This is fixed with the latest patch..check it out. and close if it fixes

**Comment by jekriske** [comment]
Fixed, nice job! 

Atom deprecation cop is complaining, but you can get around to that in the future. The preview-plus bug is more important.

**Comment by skandasoft** [comment]
out of 3 depreciation cop message only 1 valid and taken care. BTW the preview-plus bug is also resolved. check the issue.

**Comment by onecsguy** [comment]
Wondering how to update, can't open the package settings to disable this plugin or update it with this issue.

**Comment by skandasoft** [comment]
I am not sure if I understood your question. But if you wanted to get the latest on this package. I would go by clicking on the gift symbol on the status bar on the right end. it will list all updates available for the package you installed. or you could uninstall this package and reinstall to get the latest.

**Comment by onecsguy** [comment]
The error in this package caused the settings page to not load, so no simple clicking, but doing it through the terminal worked. :smile:

**Comment by mortonsworld** [comment]
Im Sorry I'm having the same issue where can i locate the patch to fix this?

**Comment by skandasoft** [comment]
can you post the break code/ report the issue from atom.. so I can see the stack trace

**Comment by mortonsworld** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.3
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.15


### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/MortonsWorld/.atom/packages/browser-plus/lib/browser-plus.coffee:31

ReferenceError: path is not defined
  at /Users/MortonsWorld/.atom/packages/browser-plus/lib/browser-plus.coffee:31:12
  at wrappedOpener (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:511:18)
  at Workspace.module.exports.Workspace.openURIInPane (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:433:22)
  at Workspace.module.exports.Workspace.open (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/workspace.js:366:19)
  at atom-workspace.atom.commands.add.settings-view:check-for-package-updates (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:74:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at HTMLAnchorElement.atom.notifications.addInfo.buttons.onDidClick (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/main.js:109:33)
  at HTMLAnchorElement.<anonymous> (/Users/MortonsWorld/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:137:42)

```

### Commands

```
  4x -0:55.7.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-light-theme.theme-one-light-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus-async, v0.22.0
browser-plus, v0.0.15
color-picker, v1.7.0
linter, v0.12.2
tab-length, v0.1.0
tag, v0.2.3

# Dev
No dev packages
```

**Comment by jekriske** [comment]
What you just posted was from the old package... delete the folder from your ~/.atom/packages folder and install the new version.

**Comment by mortonsworld** [comment]
Thank You!

**Comment by skandasoft** [comment]
assuming it worked. Please feel free to reopen
