### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getUri' of undefined

### ISSUE THREAD

**Issue by ron-wolf** [skandasoft/browser-plus#41]
Happens as soon as `browser-plus` is opened, instead of browser pane being opened. `browser-plus:history` works just fine, opening a perfectly usable browser pane. This is a near-clone of #36, which was closed for no apparent reason (besides no response).

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.38

### Stack Trace

Uncaught TypeError: Cannot read property 'getUri' of undefined

```
At /Users/Ronathan/.atom/packages/browser-plus/lib/browser-plus.coffee:83

TypeError: Cannot read property 'getUri' of undefined
  at Object.module.exports.BrowserPlus.open (/Users/Ronathan/.atom/packages/browser-plus/lib/browser-plus.coffee:83:5)
  at atom-workspace.subscriptions.add.atom.commands.add.browser-plus:open (/Users/Ronathan/.atom/packages/browser-plus/lib/browser-plus.coffee:78:20)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:02.2.0 browser-plus:open (atom-workspace.workspace.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui.scrollbars-visible-when-scrolling)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/Ronathan/Documents/Code/GitHub",
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "term"
    ]
  },
  "browser-plus": {
    "homepage": "https://duckduckgo.com",
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.38
color-picker, v2.0.13
file-icons, v1.6.11
markdown-preview-plus, v2.2.2
minimap, v4.13.4
pigments, v0.18.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can  you check if you have the latest code

**Comment by skandasoft** [comment]
would be happy to hear the feedback. Since I don't see any, assuming things are fixed. feel free to reopen

**Comment by ron-wolf** [comment]
Sorry, missed the notif. I think the fix worked.
