### ISSUE TITLE
Uncaught TypeError: jQ(...).autocomplete is not a function

### ISSUE THREAD

**Issue by MrMeatboy** [skandasoft/browser-plus#43]
I've tried to lounch browser, and when i reloaded nothing happend, except showing this error.

**Atom Version**: 1.0.19
**System**: Linux Mint
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.42

### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /home/wojtek/.atom/packages/browser-plus/lib/browser-plus-view.coffee:106

TypeError: jQ(...).autocomplete is not a function
  at BrowserPlusView.module.exports.BrowserPlusView.initialize (/home/wojtek/.atom/packages/browser-plus/lib/browser-plus-view.coffee:106:16)
  at BrowserPlusView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new BrowserPlusView (/home/wojtek/.atom/packages/browser-plus/lib/browser-plus-view.coffee:16:5)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:93:16)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:65:21)
  at atom-pane.PaneElement.getActiveView (/usr/share/atom/resources/app.asar/src/pane-element.js:210:25)
  at atom-pane.<anonymous> (/usr/share/atom/resources/app.asar/src/pane-element.js:60:55)

```

### Commands

```
     -5:15.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:00.2.0 core:paste (atom-text-editor.editor.is-focused)
  3x -4:59.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -3:18.5.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -2:19.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -2:09.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:59.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:59 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:58.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:18.9.0 tree-view:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.1.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  5x -0:11.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:07.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.6.0 browser-plus:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.6.0 symbols-view:toggle-file-symbols (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.42
minimap, v4.15.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you uninstall and reinstall

**Comment by sinithwar** [comment]
I just installed the new version and got this same error. I also uninstalled and reinstalled.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.42


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /C:/Users/Tommy/.atom/packages/browser-plus/lib/browser-plus-view.coffee:223

TypeError: jQ(...).autocomplete is not a function
  at BrowserPlusView.module.exports.BrowserPlusView.initialize (C:\Users\Tommy\.atom\packages\browser-plus\lib\browser-plus-view.coffee:106:16)
  at BrowserPlusView.View (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  at new BrowserPlusView (C:\Users\Tommy\.atom\packages\browser-plus\lib\browser-plus-view.coffee:16:5)
  at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\src\view-registry.js:93:16)
  at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\src\view-registry.js:65:21)
  at atom-pane.PaneElement.itemRemoved (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane-element.js:193:37)
  at Emitter.module.exports.Emitter.emit (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.removeItem (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:403:20)
  at Pane.module.exports.Pane.destroyItem (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\src\pane.js:466:16)
  at HTMLDivElement.<anonymous> (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:236:22)
  at space-pen-ul.jQuery.event.dispatch (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at space-pen-ul.elemData.handle (C:\Users\Tommy\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```

### Commands

```
     -1:44.4.0 settings-view:uninstall-packages (atom-text-editor.editor.is-focused)
     -1:14.8.0 core:copy (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "browser-plus": {
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.42
css-specificity, v0.2.2
run-in-browser, v0.1.3

# Dev
No dev packages
```

**Comment by smashew** [comment]
:+1:

**Comment by skandasoft** [comment]
shoot..atom is loading its own jquery..fixed it.

**Comment by skandasoft** [comment]
would be happy to hear the feedback. Since I don't see any, assuming things are fixed. feel free to reopen

**Comment by CLBarajas** [comment]
This seemed to come back for me with the latest updates, at least at some point between v0.0.61 and v0.0.64. Perhaps @manickampr might be aware whether any of their changes are contributing to this?

* * *

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809:27)
    at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:662:33)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -0:31.4.0 core:backspace (atom-text-editor#browser-plus.homepage.editor.mini.is-focused)
     -0:29.2.0 core:save (atom-text-editor#browser-plus.homepage.editor.mini.is-focused)
     -0:04.3.0 command-palette:toggle (input#toggleKeybindings.)
     -0:02.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.4.0 browser-plus:open (input#toggleKeybindings.)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "browser-plus"
    ],
    "projectHome": "/Users/ammo/Documents/GitHub"
  },
  "browser-plus": {
    "currentFile": false,
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
browser-plus, v0.0.64
linter, v1.11.14
linter-jsonlint, v1.3.0
navigate, v0.1.16
pdf-view, v0.50.0
platformio-ide-terminal, v2.1.0
pretty-json, v1.4.1
svn, v0.0.12

# Dev
No dev packages
```

**Comment by jennuine** [comment]
I am also receiving this error on a fresh install of Windows 10.

---

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:211

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (file:///C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new BrowserPlusView (file:///C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:809:27)
    at Immediate._onImmediate (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:662:33)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -0:06.3.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.64
file-icons, v1.7.16
linter, v1.11.14
minimap, v4.24.7
minimap-pigments, v0.2.1
monokai, v0.18.0
pigments, v0.31.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you check the latest patch

**Comment by CLBarajas** [comment]
Afraid not. Installed v0.0.65, restarted Atom, and tried to open from the Command Palette.

### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/ammo/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809:27)
    at Immediate._onImmediate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:662:33)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -0:05.0 command-palette:toggle (atom-pane.pane.active)
     -0:02.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.6.0 browser-plus:open (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "browser-plus"
    ],
    "projectHome": "/Users/ammo/Documents/GitHub"
  },
  "browser-plus": {
    "currentFile": false,
    "homepage": "http://www.time.gov/",
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.8.3
browser-plus, v0.0.65
linter, v1.11.14
linter-jsonlint, v1.3.0
navigate, v0.1.16
pdf-view, v0.50.0
platformio-ide-terminal, v2.1.0
pretty-json, v1.4.1
svn, v0.0.12

# Dev
No dev packages
```

**Comment by jennuine** [comment]
I installed the update and restarted atom but still get the error

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.65


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:211

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (file:///C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
    at new BrowserPlusView (file:///C:/Users/jennn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:194:25)
    at atom-pane.<anonymous> (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:51:55)
    at atom-pane.PaneElement.activated (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.activate (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:809:27)
    at Immediate._onImmediate (C:\Users\jennn\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:662:33)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

### Commands

```
     -0:05.5.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.21
browser-plus, v0.0.65
file-icons, v1.7.16
linter, v1.11.14
minimap, v4.24.7
minimap-pigments, v0.2.1
monokai, v0.18.0
pigments, v0.31.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you try one more ...with the latest patch

**Comment by CLBarajas** [comment]
Looks good to me now.

**Comment by jennuine** [comment]
Works well now, thank you!
