### ISSUE TITLE
when I clicked the down arrow in the right of the fav button or typed in the location bar, there are errors.

### ISSUE THREAD

**Issue by zaaack** [skandasoft/browser-plus#44]
**Atom Version**: 1.0.19
**System**: Deepin 2014.3
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.45

## click the down arrow button
![image](https://cloud.githubusercontent.com/assets/5233940/10777509/39610126-7d57-11e5-9856-535dbb40139c.png)

### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:14

TypeError: Cannot read property 'slice' of undefined
  at FavView.viewForItem (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:14:89)
  at FavView.module.exports.SelectListView.populateList (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
  at FavView.module.exports.SelectListView.setItems (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:167:12)
  at FavView.initialize (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:8:6)
  at FavView.View (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at FavView.SelectListView (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
  at new FavView (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:5:3)
  at HTMLSpanElement.<anonymous> (/media/z/data/home/z/.atom/packages/browser-plus/lib/browser-plus-view.coffee:330:13)
  at HTMLSpanElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /media/z/data/home/z/.atom/packages/browser-plus/lib/browser-plus-view.coffee:68

TypeError: Cannot read property 'match' of undefined
  at /media/z/data/home/z/.atom/packages/browser-plus/lib/browser-plus-view.coffee:68:65
  at arrayFilter (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1384:13)
  at Function.filter (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6309:14)
  at [object Object].source (/media/z/data/home/z/.atom/packages/browser-plus/lib/browser-plus-view.coffee:67:17)
  at [object Object].$.widget._search (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:422:8)
  at [object Object]._search (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:98:25)
  at [object Object].$.widget.search (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:414:15)
  at [object Object].search (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:98:25)
  at [object Object].<anonymous> (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:395:10)
  at handlerProxy (/media/z/data/home/z/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:427:6)

```
### Commands

```
     -1:30.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -1:23.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:23.2.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:23 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:23 browser-plus:open (atom-text-editor.editor)
  2x -0:49.8.0 core:cancel (input#uri.native-key-bindings.ui-autocomplete-input.ui-autocomplete-loading)
  2x -0:25.2.0 core:close (webview.native-key-bindings)
     -0:03.9.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "build"
    ],
    "ignoredNames": [
      "*.pyc",
      "venv"
    ],
    "autoHideMenuBar": true
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
AtomicChar, v0.3.8
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.1
autocomplete-python, v0.9.0
browser-plus, v0.0.45
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
jshint, v1.8.1
language-babel, v0.15.10
linter-scss-lint, v2.3.0
minimap, v4.15.0
minimap-autohide, v0.10.1
node-debugger, v1.1.9
package-sync, v0.2.0
pigments, v0.18.1
project-manager, v2.6.5
python-tools, v0.6.5
react, v0.12.10
tasks, v2.4.0
terminal-plus, v0.12.3
toggle-slash, v1.0.13

# Dev
No dev packages
```

**Comment by TheCherry** [comment]
same here

**Comment by skandasoft** [comment]
I have reset the state. can you try again.

**Comment by yzhen123** [comment]
@skandasoft  I upgrade the browse-plus, but this bug shows again after I clicked the fav list button

**Atom Version**: 1.0.19
**System**: Deepin 2014.3
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.52


### Stack Trace

Uncaught TypeError: Cannot read property 'slice' of undefined

```
At /media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:14

TypeError: Cannot read property 'slice' of undefined
  at FavView.viewForItem (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:14:89)
  at FavView.module.exports.SelectListView.populateList (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
  at FavView.module.exports.SelectListView.setItems (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:167:12)
  at FavView.initialize (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:8:6)
  at FavView.View (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at FavView.SelectListView (/opt/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:18:51)
  at new FavView (/media/z/data/home/z/.atom/packages/browser-plus/lib/fav-view.coffee:5:3)
  at HTMLSpanElement.<anonymous> (/media/z/data/home/z/.atom/packages/browser-plus/lib/browser-plus-view.coffee:341:13)
  at HTMLSpanElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
  2x -0:36.4.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter",
      "build",
      "jshint"
    ],
    "ignoredNames": [
      "*.pyc",
      "venv"
    ],
    "autoHideMenuBar": true
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
AtomicChar, v0.3.8
atom-ternjs, v0.8.4
autocomplete-modules, v1.3.1
autocomplete-python, v0.9.2
browser-plus, v0.0.52
color-picker, v2.0.13
emmet, v2.3.13
file-icons, v1.6.11
language-babel, v0.15.12
linter-scss-lint, v2.4.0
minimap, v4.15.0
minimap-autohide, v0.10.1
node-debugger, v1.1.9
package-sync, v0.2.0
pigments, v0.18.1
project-manager, v2.6.5
python-tools, v0.6.5
react, v0.12.10
tasks, v2.4.0
terminal-plus, v0.12.3
toggle-slash, v1.0.13

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
so you tried to favoritize the current file..I have added a open-current to the list of browser-plus command and fixed the issue. Please try the latest patch

**Comment by skandasoft** [comment]
closing it ..since there are no updates..reopen if it is not resolved.
