### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by TheCherry** [skandasoft/browser-plus#45]
browser-plus: 0.0.45
atom: 1.0.19
system: ubuntu 64bit
Then I type something into the url textbox, that error comes:
```
TypeError: Cannot read property 'match' of undefined
  at /home/xxx/.atom/packages/browser-plus/lib/browser-plus-view.coffee:68:65
  at arrayFilter (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:1384:13)
  at Function.filter (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/lodash/index.js:6309:14)
  at [object Object].source (/home/xxx/.atom/packages/browser-plus/lib/browser-plus-view.coffee:67:17)
  at [object Object].$.widget._search (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:422:8)
  at [object Object]._search (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:98:25)
  at [object Object].$.widget.search (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:414:15)
  at [object Object].search (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:98:25)
  at [object Object].<anonymous> (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/autocomplete.js:395:10)
  at handlerProxy (/home/xxx/.atom/packages/browser-plus/node_modules/jquery-ui/widget.js:427:6)
```

**Comment by skandasoft** [comment]
can you check the latest version

**Comment by skandasoft** [comment]
closing since there are no updates..feel free to reopen
