### ISSUE TITLE
Uncaught TypeError: _this.refresh is not a function

### ISSUE THREAD

**Issue by MustafaAdam** [skandasoft/browser-plus#66]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: elementary OS
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.56

### Stack Trace

Uncaught TypeError: _this.refresh is not a function

```
At /home/mustafa/.atom/packages/browser-plus/lib/browser-plus-view.coffee:278

TypeError: _this.refresh is not a function
    at HTMLSpanElement.<anonymous> (/home/mustafa/.atom/packages/browser-plus/lib/browser-plus-view.coffee:278:12)
    at HTMLSpanElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:26.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:26.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:26.6.0 editor:indent (atom-text-editor.editor.is-focused)
  2x -0:25.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:24.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.1.0 run:script (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-java",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-ruby",
      "language-ruby-on-rails",
      "linter-pep8"
    ],
    "themes": [
      "atom-dark-ui",
      "gruvbox-syntax"
    ]
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.2
atom-jinja2, v0.5.0
autoclose-html, v0.23.0
autocomplete-python, v1.7.2
browser-plus, v0.0.56
file-icons, v1.7.1
gruvbox-syntax, v1.2.0
highlight-selected, v0.11.2
linter, v1.11.4
python-autopep8, v0.1.3
python-snippets, v1.1.0
python-tools, v0.6.7
script-runner, v1.8.4
terminal-plus, v0.14.5

# Dev
No dev packages
```

I keep getting errors whenever I try the browser plugin with a simple flask app. This error pops up whenver I press the "Live" button on the browser plus

**Comment by skandasoft** [comment]
fixed it..but unable to upload because of bad connection. check back in couple of hours

**Comment by skandasoft** [comment]
caan you try now

**Comment by lautr3k** [comment]
1. Update to v0.0.57
2. Click on Live button

**Atom Version**: 1.6.2
**System**: Windows 10
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.57


### Stack Trace

Uncaught TypeError: _this.refresh is not a function

```
At /C:/Users/skarab/.atom/packages/browser-plus/lib/browser-plus-view.coffee:530

TypeError: _this.refresh is not a function
    at HTMLSpanElement.<anonymous> (file:///C:/Users/skarab/.atom/packages/browser-plus/lib/browser-plus-view.coffee:278:12)
    at HTMLSpanElement.jQuery.event.dispatch (C:\Users\skarab\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (C:\Users\skarab\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
 44x -9:51 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -7:56.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
 29x -7:53.8.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -4:09.0 find-and-replace:show (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "simple-drag-drop-text",
      "atom-html-preview",
      "docblockr",
      "minimap-pigments",
      "preview-plus"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "autoclose-html"
    ],
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autoclose-html, v0.23.0
browser-plus, v0.0.57
highlight-selected, v0.11.2
line-ending-converter, v1.3.2
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
open-recent, v5.0.0
pigments, v0.26.0
seti-icons, v0.4.5

# Dev
No dev packages
```

**Comment by lautr3k** [comment]
3. Re-Click on Live button

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.57


### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /C:/Users/skarab/.atom/packages/browser-plus/lib/browser-plus-view.coffee:546

TypeError: Cannot read property 'dispose' of undefined
    at HTMLSpanElement.<anonymous> (file:///C:/Users/skarab/.atom/packages/browser-plus/lib/browser-plus-view.coffee:289:28)
    at HTMLSpanElement.jQuery.event.dispatch (C:\Users\skarab\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (C:\Users\skarab\AppData\Local\atom\app-1.6.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

**Comment by MustafaAdam** [comment]
I've updated to v0.0.57 and got the same error as as lautr3k have posted.
""""
'Uncaught TypeError: Cannot read property 'dispose' of undefined'

/home/mustafa/.atom/packages/browser-plus/lib/browser-plus-view.coffee:289

TypeError: Cannot read property 'dispose' of undefined
    at HTMLSpanElement.<anonymous> (/home/mustafa/.atom/packages/browser-plus/lib/browser-plus-view.coffee:289:28)
    at HTMLSpanElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLSpanElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
"""""

**Comment by skandasoft** [comment]
can you check the latest version

**Comment by MustafaAdam** [comment]
It's working well so far. Thank you guys :)
