### ISSUE TITLE
Uncaught Error: Error processing argument -1.TypeError: Error processing argument -1.    at Typ...

### ISSUE THREAD

**Issue by guchenghao** [skandasoft/browser-plus#68]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.4
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.57

### Stack Trace

Uncaught Error: Error processing argument -1.
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.webContents.executeJavaScript (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:69:21)
    at callFunction (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:174:18)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:260:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110

Error: Error processing argument -1.
TypeError: Error processing argument -1.
    at TypeError (native)
    at EventEmitter.webContents.executeJavaScript (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:69:21)
    at callFunction (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:174:18)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:260:14)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:99:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:15)
    at EventEmitter.RemoteMemberFunction [as executeJavaScript] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:144:26)
    at webview.executeJavaScript (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:290:48)
    at /Users/guchenghao/.atom/packages/browser-plus/lib/browser-plus-view.coffee:223:32
```

### Commands

```
     -0:04.3.0 browser-plus:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-light"
    ]
  },
  "browser-plus": {
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-handlebars, v1.3.0
atom-material-syntax-light, v0.4.5
atom-material-ui, v1.2.10
atom-ternjs, v0.13.2
autocomplete-modules, v1.4.1
autocomplete-php, v0.3.7
autocomplete-python, v1.7.2
browser-plus, v0.0.57
color-picker, v2.1.1
css-snippets, v0.9.0
docblockr, v0.7.3
file-icons, v1.7.1
file-type-icons, v1.0.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
javascript-snippets, v1.2.1
jshint, v1.8.5
language-ejs, v0.2.0
language-jade, v0.7.1
linter, v1.11.4
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
minimap-selection, v4.4.0
pigments, v0.26.0
rest-client, v1.0.0
terminal-panel, v1.14.1
vim-mode, v0.65.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
can you check the latest version?
