### ISSUE TITLE
Errors in console: font-awesome net::ERR_FILE_NOT_FOUND when launching atom

### ISSUE THREAD

**Issue by Ben3eeE** [skandasoft/browser-plus#69]
I get the following error when I start/reload atom with browser-plus enabled. Disabling browser-plus removes the error message on start/reload of atom.
I have not seen this error message since before I updated the package today, version now is 0.0.60.

```
GET file:///C:/Users/lineri/AppData/Local/atom/app-1.6.2/resources/app.asar/static/font-awesome.min.css net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/lineri/AppData/Local/atom/app-1.6.2/resources/app.asar/fonts/fontawesome-webfont.woff2?v=4.5.0 net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/lineri/AppData/Local/atom/app-1.6.2/resources/app.asar/fonts/fontawesome-webfont.woff?v=4.5.0 net::ERR_FILE_NOT_FOUND
GET file:///C:/Users/lineri/AppData/Local/atom/app-1.6.2/resources/app.asar/fonts/fontawesome-webfont.ttf?v=4.5.0 net::ERR_FILE_NOT_FOUND
```

Windows 7
Atom 1.6.2

**Comment by skandasoft** [comment]
removing font-awesome..since I think it is not needed for this package letz see if it fixes this.

**Comment by Ben3eeE** [comment]
Still see this error when activating the package, go to settings-view, open console:

Disable browser-plus:
```
C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:652 Error deactivating package 'browser-plus' TypeError: Cannot read property 'destroy' of null
    at Object.module.exports.BrowserPlus.deactivate (file:///C:/Users/lineri/.atom/packages/browser-plus/lib/browser-plus.coffee:112:5)
    at Package.module.exports.Package.deactivate (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:641:21)
    at PackageManager.module.exports.PackageManager.deactivatePackage (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:622:12)
    at C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:337:21
    at C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:816:29)
    at Config.module.exports.Config.setRawValue (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:608:19)
    at Config.module.exports.Config.set (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:227:14)
    at Config.module.exports.Config.pushAtKeyPath (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:361:12)
    at Package.module.exports.Package.disable (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:81:26)
    at PackageManager.module.exports.PackageManager.disablePackage (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:179:16)
    at HTMLButtonElement.<anonymous> (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\package-card.js:326:27)
    at HTMLButtonElement.jQuery.event.dispatch (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

Enable browser plus:
```
C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:5211 GET file:///C:/Users/lineri/AppData/Local/atom/app-1.9.9/resources/app.asar/fonts/fontawesome-webfont.woff2?v=4.5.0 net::ERR_FILE_NOT_FOUND(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:5211jQuery.extend.each @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:374jQuery.fn.jQuery.each @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:139(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:5209jQuery.access @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:3491jQuery.fn.extend.text @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:5206module.exports.PackageCard.displayDisabledState @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\pack…:395module.exports.PackageCard.updateDisabledState @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\pack…:377(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\pack…:560(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:631module.exports.Emitter.simpleDispatch @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.…:25module.exports.Emitter.emit @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.…:125module.exports.Config.emitChangeEvent @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:816module.exports.Config.setRawDefault @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:649module.exports.Config.setDefaults @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:666module.exports.Config.setDefaults @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:661module.exports.Config.setSchema @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:406module.exports.Package.registerConfigSchemaFromMainModule @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:211module.exports.Package.activateNow @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:175(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:156module.exports.Package.measure @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:92(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:149module.exports.Package.activate @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:146module.exports.PackageManager.activatePackage @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:538(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:342(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:631module.exports.Emitter.simpleDispatch @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.…:25module.exports.Emitter.emit @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\event-kit\lib\emitter.…:125module.exports.Config.emitChangeEvent @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:816module.exports.Config.setRawValue @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:608module.exports.Config.set @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:227module.exports.Config.removeAtKeyPath @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\config.js:377module.exports.Package.enable @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package.js:77module.exports.PackageManager.enablePackage @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\package-manager.js:169(anonymous function) @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\settings-view\lib\pack…:324jQuery.event.dispatch @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4435elemData.handle @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\node_modules\jquery\dist\jquery.js:4121
```

Open browser plus window with ctrl-shift-o
```
(electron) getUrl is deprecated. Use getURL instead.
C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\state-store.js:33 Uncaught (in promise) DOMException: Failed to execute 'put' on 'IDBObjectStore': An object could not be cloned.(…)dbPromise.then.db @ C:\Users\lineri\AppData\Local\atom\app-1.9.9\resources\app.asar\src\state-store.js:33
```
