### ISSUE TITLE
Uncaught TypeError: this.iconName.split is not a function

### ISSUE THREAD

**Issue by 50Wliu** [skandasoft/browser-plus#75]
_From @planvin on May 23, 2016 13:47_

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.4
**Thrown From**: [tabs](https://github.com/atom/tabs) package, v0.96.0

### Stack Trace

Uncaught TypeError: this.iconName.split is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325

TypeError: this.iconName.split is not a function
    at tabs-tab.module.exports.TabView.updateIcon (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:325:63)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-view.js:123:24
    at HTMLEditor.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/node_modules/emissary/lib/emitter.js:118:15)
    at HTMLEditor.module.exports.HTMLEditor.updateIcon (/Users/pierre/.atom/packages/browser-plus/lib/browser-plus-model.coffee:69:8)
    at webview.<anonymous> (/Users/pierre/.atom/packages/browser-plus/lib/browser-plus-view.coffee:233:16)
    at WebViewImpl.dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:188:29)
    at dispatchEvent (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:56:11)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/guest-view-internal.js:67:28)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -1:40.8.0 command-palette:toggle (atom-pane.pane.active)
     -1:38.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:37.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:37.4.0 browser-plus:open (atom-pane.pane.active)
     -1:12.7.0 pane:split-right (atom-pane.pane.active)
     -0:47.5.0 jekyll:toggle-server (input#uri.native-key-bindings.ui-autocomplete-input)
  2x -0:32.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
browser-plus, v0.0.60
jekyll, v1.4.1
language-liquid, v0.5.1
language-scala, v1.1.6
pretty-json, v0.4.1

# Dev
No dev packages
```

_Copied from original issue: atom/tabs#328_

**Comment by BlaM** [comment]
I see this error every time I pick another page in the DevDocs through the navigation menu.

**Comment by Jonahss** [comment]
I'm also encountering this error. any ideas?

**Comment by jclpub** [comment]
Same here.

**Comment by eladcandroid** [comment]
And here... (Atom v1.8.0)

**Comment by rpmonteiro** [comment]
Here too. Unusable like this

**Comment by Jonahss** [comment]
Usable, just annoying.

I'd like to fix it, but im blocked by this: 
https://github.com/skandasoft/browser-plus/issues/81

**Comment by aadityataparia** [comment]
+1
This is really annoying.

**Comment by bkawakami** [comment]
+1

**Comment by ferminarellano** [comment]
+1

**Comment by Quantaliinuxite** [comment]
I submitted a pull request to fix this. I think the issue does belong in the tabs package though.

**Comment by Jonahss** [comment]
link to the PR?

**Comment by Quantaliinuxite** [comment]
https://github.com/skandasoft/browser-plus/pull/83

The error arises when we try to tell the tab there's a new favicon. I wonder if the tabs API is changed and we simply need to update browser-plus's code. In the meantime, this prevents the red alert from popping up every time

**Comment by Jonahss** [comment]
Nice.

I'm thinking about writing a new version of this plugin, since we're not hearing back from the maintainer, and I'm blocked on #81

If I do, I'll post here ^.^

**Comment by Quantaliinuxite** [comment]
I created a more permanent fix, this is the PR: https://github.com/skandasoft/browser-plus/pull/84

**Comment by skandasoft** [comment]
I applied it. Enjoy :+1:

**Comment by skandasoft** [comment]
This is issue should have been fixed with merge.
