### ISSUE TITLE
Uncaught TypeError: Array.observe is not a function

### ISSUE THREAD

**Issue by aki237** [skandasoft/browser-plus#77]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.4
**System**: "Arch Linux"
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.60

### Stack Trace

Uncaught TypeError: Array.observe is not a function

```
At /home/aki237/.atom/packages/browser-plus/lib/browser-plus-view.coffee:148

TypeError: Array.observe is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/home/aki237/.atom/packages/browser-plus/lib/browser-plus-view.coffee:148:15)
    at BrowserPlusView.View [as constructor] (/usr/lib/atom/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/home/aki237/.atom/packages/browser-plus/lib/browser-plus-view.coffee:25:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/lib/atom/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/lib/atom/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/usr/lib/atom/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/usr/lib/atom/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/usr/lib/atom/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/usr/lib/atom/src/pane.js:809:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/usr/lib/atom/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/usr/lib/atom/node_modules/notifications/lib/notification-element.js:248:19)
    at /usr/lib/atom/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/lib/atom/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/usr/lib/atom/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/usr/lib/atom/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/usr/lib/atom/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
     -2:15.8.0 snippets:expand (atom-text-editor.editor.is-focused)
     -2:15.8.0 editor:indent (atom-text-editor.editor.is-focused)
  3x -2:13.8.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -2:12.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:10.9.0 find-and-replace:show (atom-text-editor.editor.is-focused.mini)
     -2:08.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -2:08.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -2:07.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:04.1.0 pane:show-item-2 (atom-text-editor.editor.is-focused.mini)
     -0:57.9.0 command-palette:toggle (div.package-readme.native-key-bindings)
     -0:54.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:54.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.7.0 browser-plus:open (div.package-readme.native-key-bindings)
     -0:35 core:cancel (atom-pane.pane.active)
     -0:19.2.0 pane:show-item-2 (ul.list-inline.tab-bar.inset-panel)
     -0:18.9.0 pane:show-item-3 (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax-dark, v0.2.5
atom-material-ui, v1.2.12
atomic-emacs, v0.9.1
autocomplete-go, v1.1.0
browser-plus, v0.0.60
builder-go, v1.0.0
go-config, v1.1.4
go-get, v1.0.3
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
linter, v1.11.4
navigator-godef, v1.0.3
preview-plus, v1.2.6
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
Please check the latest patch and feel free to reopen if the issue still exit
