### ISSUE TITLE
Uncaught Error: Cannot find module 'simplestorage.js'

### ISSUE THREAD

**Issue by shouta2424** [skandasoft/browser-plus#86]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.63

### Stack Trace

Uncaught Error: Cannot find module 'simplestorage.js'

```
At module.js:340

Error: Cannot find module 'simplestorage.js'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.serialize (file:///C:/Users/nishimoto/.atom/packages/browser-plus/lib/browser-plus-model.coffee:62:12)
    at C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:100:23
    at Array.map (native)
    at Pane.module.exports.Pane.serialize (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:99:36)
    at C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-axis.js:50:24
    at Array.map (native)
    at PaneAxis.module.exports.PaneAxis.serialize (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-axis.js:49:33)
    at PaneContainer.module.exports.PaneContainer.serialize (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-container.js:54:51)
    at Workspace.module.exports.Workspace.serialize (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:154:43)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:770:35)
    at C:\Users\nishimoto\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:984:27
```

### Commands

```
  2x -1:05.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:10 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "atom-dark-ui-slim",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-dark-ui-slim, v0.47.1
auto-encoding, v0.5.7
autoclose-html, v0.23.0
autocomplete-paths, v1.0.2
browser-plus, v0.0.63
color-picker, v2.1.1
file-icons, v1.7.16
highlight-column, v0.5.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
japanese-menu, v1.8.0
linter, v1.11.14
linter-csslint, v1.3.2
linter-htmlhint, v1.2.1
linter-jshint, v2.1.0
minimap, v4.24.6
minimap-autohide, v0.10.1
pigments, v0.30.0
sync-settings, v0.7.2
tablr, v1.3.1
tag, v0.4.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
fixed..check the patch.
