### ISSUE TITLE
Uncaught TypeError: jQ(...).autocomplete is not a function

### ISSUE THREAD

**Issue by raflemin12** [skandasoft/browser-plus#88]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.65
### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/raflemin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/raflemin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/raflemin/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:414:19)
    at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:369:21)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:562:16)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.closeTab (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:321:26)
    at atom-tabs.TabBarView.closeAllTabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:452:28)
    at Object.addElementCommands.tabs:close-all-tabs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:120:26)
    at atom-tabs.commandsWithPropagationStopped.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:86:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
  3x -3:24.6.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -3:18.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:55.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:48.6.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:29.9.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused)
 12x -2:24.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:08.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -2:06.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:56.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:51.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:42.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:39.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:30.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:24.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:29.2.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -0:00.9.0 tabs:close-all-tabs (div.title)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "an-old-hope-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
an-old-hope-syntax, v0.5.0
atom-beautify, v0.29.9
atom-html-preview, v0.1.21
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
browser-plus, v0.0.65
color-picker, v2.1.1
file-icons, v1.7.16
linter, v1.11.14
minimap, v4.24.7
pigments, v0.31.0

# Dev
No dev packages
```

**Comment by codekraft-studio** [comment]
i had the same issue right now, just installed the package for tryin and when I open it it says many times "Uncaught TypeError: jQ(...).autocomplete is not a function"


```
# atom -v

Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
```

**Stack trace**
```
TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/home/user/.atom/packages/browser-plus/lib/browser-plus-view.coffee:102:16)
    at BrowserPlusView.View [as constructor] (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/home/user/.atom/packages/browser-plus/lib/browser-plus-view.coffee:27:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/usr/share/atom/resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/usr/share/atom/resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/usr/share/atom/resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:809:27)
    at Immediate._onImmediate (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:662:33)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

how did you fixed it, in your case?

**Comment by skandasoft** [comment]
check FAQ. also try going to cmd prompt and into the browser-plus directory and 
``` 
npm install
```

**Comment by codekraft-studio** [comment]
I did it, and I did all of the things described in the FAQ but I still have the problem I've also downloaded the github version and tried with that but is not working.

**Comment by skandasoft** [comment]
Can you delete the Jquery/ui directory and do a npm install again in the browser-plus directory

**Comment by codekraft-studio** [comment]
I tried by removing jquery-ui:
```
apm rebuild-module-cache  // as described in FAQ
rm -rf node_modules/jquery*
npm install
```
but I get the same error as soon as I focus the address bar :[

**Comment by skandasoft** [comment]
can you share a screen shot of node_modules/jquery_ui/ directory and package.json details for dependencies

**Comment by Shadizzle** [comment]
Also having this same problem. Why is this issue closed?

jquery-ui directory:
[1](https://cloud.githubusercontent.com/assets/7839325/20312551/a6e5e8ec-ab32-11e6-9bbb-affa1da85b0d.png)
[2](https://cloud.githubusercontent.com/assets/7839325/20312550/a6e2593e-ab32-11e6-8416-8a27bf8c9678.png)

package.json of browser-plus and jquery-ui in node_modules:
[browser-plus](https://github.com/skandasoft/browser-plus/files/592468/browser_plus_package_json.txt)
[jquery-ui](https://github.com/skandasoft/browser-plus/files/592469/jquery_ui_package_json.txt)

**Comment by skandasoft** [comment]
That is exactly how it needs to be. The jquery 1.10.5 looks fine. I am not sure why jQ.autocomplete will not be available after the require statement works. I am going to open it this again to see if anybody else can throw some light.

**Comment by Kutoru** [comment]
Building it manually as #98 says fixes it for me.

**Comment by Rjavey** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.87


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /C:/Users/Administrator/.atom/packages/browser-plus/lib/browser-plus-view.coffee:36

TypeError: jQ(...).autocomplete is not a function
    at file:///C:/Users/Administrator/.atom/packages/browser-plus/lib/browser-plus-view.coffee:21:16
    at Emitter.module.exports.Emitter.emit (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at HTMLEditor.module.exports.HTMLEditor.destroyed (file:///C:/Users/Administrator/.atom/packages/browser-plus/lib/browser-plus-model.coffee:38:16)
    at HTMLEditor.module.exports.Model.destroy (C:\Users\Administrator\.atom\packages\browser-plus\node_modules\theorist\lib\model.js:218:14)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\src\pane.js:451:18)
    at atom-tabs.TabBarView.onClick (C:\Users\Administrator\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:695:17)
```

### Commands

```
  2x -9:39.5.0 tree-view:remove (span.name.icon.icon-file-directory)
     -7:16.5.0 pane:split-down (atom-pane.pane.active)
     -7:11.7.0 pane:split-up (atom-pane.pane.active)
  2x -7:07.2.0 pane:close (atom-pane.pane.active)
     -7:02.2.0 pane:split-left (atom-pane.pane.active)
     -6:44.3.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -6:41 browser-plus:open (atom-text-editor.editor.is-focused)
     -6:22.5.0 pane:split-right (webview.native-key-bindings)
     -3:06.7.0 window:toggle-menu-bar (atom-text-editor.editor.is-focused)
     -2:59.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:54.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:51.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:51.9.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -0:43.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:21.6.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -0:08.5.0 pane:split-right (atom-pane.pane.active)
```

### Config

```json
{
  "core": {},
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.87
emmet, v2.4.3
emmet-atom-master, vundefined
pigments, v0.33.1

# Dev
No dev packages
```

**Comment by Likivik** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.1 x64
**Electron**: 1.4.15
**OS**: "Manjaro Linux"
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.87


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /home/likivik/.atom/packages/browser-plus/lib/browser-plus-view.coffee:366

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.goToUrl (/packages/browser-plus/lib/browser-plus-view.coffee:366:16)
    at /packages/browser-plus/lib/browser-plus-view.coffee:345:12)
    at HTMLInputElement.dispatch (/usr/lib/atom/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/usr/lib/atom/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:39.9.0 command-palette:toggle (atom-pane.pane.active)
  4x -5:35.8.0 core:move-down (input.hidden-input)
     -5:35 core:move-up (input.hidden-input)
     -5:34.7.0 core:confirm (input.hidden-input)
     -5:34.7.0 browser-plus:openCurrent (atom-pane.pane.active)
     -5:17.4.0 tree-view:copy-project-path (span.name.icon.icon-file-text)
     -5:12.9.0 tree-view:copy-full-path (span.name.icon.icon-file-text)
  2x -3:37.5.0 core:save (atom-pane.pane.active)
  2x -3:28 key-binding-resolver:toggle (input.hidden-input)
     -3:26 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.87 
emmet 2.4.3 
```

**Comment by Likivik** [comment]
Experiencing this too

**Comment by leojf1** [comment]
Hey guys. I had the same experience. After installing 'browser-plus' from 'package' menu, I started the server and got the answer "Uncaught TypeError: jQ(...).autocomplete is not a function".

To solve this problem, I've just closed Atom and started it again. That's it! I hope it helps you too.

**Comment by renenadorp** [comment]
Hi all,
I had the same issue. 
I installed package "autocomplete" and that solved it.
Hope that helps.

**Comment by skandasoft** [comment]
check the latest patch ....if still issue try  running **apm rebuild-module-cache** on the atom packages directory

**Comment by JLUrban** [comment]
Hi, I'm getting this error too and I tried running `apm rebuild-module-cache` and it did not work.

Here is the error Atom threw: [Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package 0.0.91


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At C:\Users\urban\.atom\packages\browser-plus\lib\browser-plus-view.coffee:375

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.goToUrl (/packages/browser-plus/lib/browser-plus-view.coffee:375:16)
    at /packages/browser-plus/lib/browser-plus-view.coffee:354:12)
    at HTMLInputElement.dispatch (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLInputElement.elemData.handle (/packages/browser-plus/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -5:05.9.0 command-palette:toggle (atom-pane.pane.active)
     -5:04.5.0 browser-plus:open (input.hidden-input)
     -2:40.3.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -2:37.1.0 browser-plus:open (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.91 
Hydrogen 1.16.0 
```

**Comment by skandasoft** [comment]
try uninstalling the package and reinstalling again.and then apm rebuild-module-cache

**Comment by JLUrban** [comment]
It still gives what appears to be the same error message

**Comment by skandasoft** [comment]
I just took care of jquery/autocomplete...check the latest patch

**Comment by AndresMendozaOrozco** [comment]
Hello,

Same error; I’ve followed the indications under 0. On FAQ. Not working.
The package is up to date. Do you have another link to the patch you’re mentioning?

Rgrds

**Comment by skandasoft** [comment]
yes one more patch ...try that...

**Comment by skandasoft** [comment]
There is some other package which is overwriting the jquery autocomplete plugin..so I have switched off the dropdown search help from bing/google as you type in the url bar for those who are having issues..for now
