### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isWaitingForResponse' of undefined

### ISSUE THREAD

**Issue by LucasArkana** [skandasoft/browser-plus#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.22

### Stack Trace

Uncaught TypeError: Cannot read property 'isWaitingForResponse' of undefined

```
At /Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:284

TypeError: Cannot read property 'isWaitingForResponse' of undefined
  at webview.isWaitingForResponse (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/lib/web-view/web-view.js:284:77)
  at /Users/Lucas-Arkana/.atom/packages/browser-plus/lib/browser-plus-view.coffee:280:25
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -8:43.4.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -8:43.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
  2x -8:42.8.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -8:42.4.0 command-palette:toggle (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -8:39 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:39 markdown-preview:toggle (atom-text-editor.editor.vim-mode.command-mode)
 41x -8:37.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -8:33.4.0 core:close (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -8:31.9.0 command-palette:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  5x -8:25.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:23.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -8:23.7.0 browser-plus:open (atom-text-editor.editor.vim-mode.command-mode)
  2x -2:22 core:cancel (div.markdown-preview.native-key-bindings)
     -1:04.6.0 core:close (atom-pane.pane.active)
     -0:08.6.0 core:cancel (atom-pane.pane.active)
  3x -0:04.9.0 core:close (webview.native-key-bindings)
```

### Config

```json
{
  "core": {},
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.22
script, v2.23.0
term2, v0.9.8
vim-mode, v0.49.0

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
This happens only when there is an error in the page's js.will look at it...please report if you have for every site..

**Comment by skandasoft** [comment]
I am not seeing this now for quite some time... so closing for now. will open if necessary.
