### ISSUE TITLE
Uncaught TypeError: Cannot read property 'startsWith' of undefined

### ISSUE THREAD

**Issue by marcwright** [skandasoft/browser-plus#90]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught TypeError: Cannot read property 'startsWith' of undefined

```
At /Users/marcwright/.atom/packages/browser-plus/lib/browser-plus-view.coffee:37

TypeError: Cannot read property 'startsWith' of undefined
    at Function.module.exports.BrowserPlusView.content (/Users/marcwright/.atom/packages/browser-plus/lib/browser-plus-view.coffee:37:18)
    at Function.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
    at BrowserPlusView.View [as constructor] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:155:33)
    at new BrowserPlusView (/Users/marcwright/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:809:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
  2x -1:07.8.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -1:06.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:05.7.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
 11x -1:04.3.0 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -1:02.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:59.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:59.6.0 core:move-down (atom-text-editor.editor.is-focused)
  8x -0:59.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:57.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  4x -0:56.5.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:42.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  7x -0:41.9.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:38.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.3.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
browser-plus, v0.0.67

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
I am not sure when this would happen. But I still put handles for it not to happen. Check the latest version.
