### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by TimurMelnikov** [skandasoft/browser-plus#94]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/timur/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (file:///C:/Users/timur/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (file:///C:/Users/timur/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:637:16)
    at atom-tabs.TabBarView.onClick (C:\Users\timur\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:688:17)
```

### Commands

```
     -0:15.8.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-html-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
browser-plus, v0.0.67
color-picker, v2.2.1
emmet, v2.4.3
file-icons, v1.7.16
highlight-selected, v0.11.2

# Dev
No dev packages
```

**Comment by litt1e-p** [comment]
I got this bug too, it keeps show alerts and can not close, so sad...

**Comment by marceloolima** [comment]
I got this bug too

**Comment by lfaler** [comment]
I have the same bug...

**Comment by yowangbin** [comment]
I got the same bug,and can not close..

**Comment by jordansteeves** [comment]
Same here.

**Comment by lfaler** [comment]
Yes it doesn't close and the error loops. After it occurs, you have to restart Atom

**Comment by jennuine** [comment]
I am getting the same error on OS X 10.11.4
___
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67


### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Jenn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/Users/Jenn/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/Users/Jenn/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.itemRemoved (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:180:37)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:568:20)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:637:16)
    at atom-tabs.TabBarView.onClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:688:17)
```

### Commands

```
     -0:02.9.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "automaticallyUpdate": false,
    "disabledPackages": [
      "meteor-helper",
      "bookmarks",
      "language-SCSS",
      "linter",
      "linter-csslint",
      "linter-htmlhint",
      "linter-jshint",
      "linter-scss-lint",
      "project-manager",
      "about",
      "autocomplete-snippets",
      "background-tips",
      "open-in-browser",
      "pdf-view",
      "tabs-to-spaces",
      "activate-power-mode",
      "atom-ng-attr-hint",
      "autocomplete-html",
      "browser-refresh-on-save",
      "browser-refresh"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "browser-plus": {
    "node": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
atom-html-preview, v0.1.21
browser-plus, v0.0.67
color-picker, v2.2.2
emmet, v2.4.3
file-icons, v1.7.16
jshint, v1.8.5
minimap, v4.24.7
monokai, v0.18.0
pigments, v0.31.1

# Dev
No dev packages
```

**Comment by BlaM** [comment]
When I try to move the tab the error reappears and now I have two identical (broken) tabs.

**Comment by jennuine** [comment]
I was able to quickly fix this issue on OS X by installing jquery-autocomplete:

```
cd ~/.atom/packages/browser-plus
npm install jquery-autocomplete --save
```

In .atom/packages/browser-plus/lib/browser-plus-view.coffee, update `require 'jquery-ui/autocomplete'` at line 4 to `require 'jquery-autocomplete'`.

You may have to add `jQuery = require('../jquery/dist/jquery.js');` in atom/packages/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js 

After relaunching Atom was able to use it without issues.

**Comment by lfaler** [comment]
That did not work for me unfortunately

**Comment by jennuine** [comment]
What was your error message?

**Comment by lfaler** [comment]
Well this is even worse, there was none

**Comment by lfaler** [comment]
It just doesn't work

**Comment by lfaler** [comment]
After that fix, atom shuts down completely after 5 minutes, so I had to
uninstall the package completely, but looking forward for the updated
version

**Comment by djmbritt** [comment]
Thanks jennuine, that worked for me.

**Comment by litt1e-p** [comment]
@jennuine , thanks, it works

**Comment by lfaler** [comment]
@jennuine Thank you! This worked for me, another package "preview-plus" was crashing my editor

**Comment by ZandorZ** [comment]
@jennuine thank you!

**Comment by mayur14** [comment]
@jennuine  Thanks!!

**Comment by kuzrwkd** [comment]
@jennuine Thank you, it great!

**Comment by skandasoft** [comment]
#98

**Comment by ninthart** [comment]
@jennuine Thank you!

**Comment by BarbaLoira** [comment]
@jennuine what line add "jQuery = require('../jquery/dist/jquery.js');" ???

**Comment by jennuine** [comment]
Line 1

**Comment by BarbaLoira** [comment]
@jennuine tks, work!!!

**Comment by gaxiiiiiiiiiiii** [comment]
@jennuine that doesn't work well. the new tab for browsing shows the file:jquery.autocomplete.js and there is no error message. do you have any ideas?

**Comment by mohandast52** [comment]
atom/packages/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js
i couldn't see this...help please!!
