### ISSUE TITLE
Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by Kacppian** [skandasoft/browser-plus#95]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Kali GNU/Linux
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught ReferenceError: jQuery is not defined

```
At /home/kaushikasp/.atom/packages/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js:1092

ReferenceError: jQuery is not defined
    at Object.<anonymous> (/home/kaushikasp/.atom/packages/browser-plus/node_modules/jquery-autocomplete/jquery.autocomplete.js:1092:3)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/kaushikasp/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/kaushikasp/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/kaushikasp/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.activeItemChanged (/usr/share/atom/resources/app.asar/src/pane-element.js:132:29)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:282:22)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:494:14)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:428:14)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:658:19)
```

### Commands

```
     -0:28 navigate:browser (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
autocomplete-clang, vundefined
browser-plus, v0.0.67
browser-refresh, v0.9.0
color-picker, v2.2.2
linter-clang, v3.4.4
linter-cpplint, v1.0.1
monokai-seti, v0.7.0
navigate, v0.1.16
project-manager, v2.9.7
seti-ui, v1.3.1

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
#43
