### ISSUE TITLE
Open-In-Browser: Instant error

### ISSUE THREAD

**Issue by lfaler** [skandasoft/browser-plus#97]
Description:

The Open-In-Browser package shows an error instantly upon the start of opening Atom
![screen shot 2016-07-23 at 11 36 02 pm](https://cloud.githubusercontent.com/assets/14255968/17082318/d8a4a64c-512e-11e6-8329-6bf3be4a5a35.png)

Error:
![screen shot 2016-07-23 at 11 44 58 pm](https://cloud.githubusercontent.com/assets/14255968/17082346/837cd04e-512f-11e6-9fdd-04cdbd8e67e6.png)
--------------------------------------------------------------------------------------------------
TypeError: Cannot read property 'get' of undefined
    at Object.module.exports.BrowserPlus.activate (/Users/laynefaler/.atom/packages/browser-plus/lib/browser-plus.coffee:37:64)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
--------------------------------------------------------------------------------------------------

Steps To Reproduce:
1. Download package
2. Close Atom
3. Open Atom

Expected Behavior: No errors
Actual Behavior: Instant error with no functionality

Versions:

MacBook-Pro:Desktop laynefaler$ atom --version
Atom    : 1.8.0
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1
MacBook-Pro:Desktop laynefaler$ apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.1

Package Version:
****** browser-plus@0.0.67 ******

**Comment by skandasoft** [comment]
Please check the latest patch and feel free to reopen if the issue still exit

**Comment by skandasoft** [comment]
once installed, can you check if the browser-plus folder in packages node_modules/jstorage

**Comment by lfaler** [comment]
It still exists, I'll write a new thread
