### ISSUE TITLE
Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

### ISSUE THREAD

**Issue by rdbl** [skandasoft/browser-plus#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04.1
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.67

### Stack Trace

Uncaught Error: Cannot find module 'jquery-ui/autocomplete'

```
At module.js:340

Error: Cannot find module 'jquery-ui/autocomplete'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/rdbl/.atom/packages/browser-plus/lib/browser-plus-view.coffee:4:1)
    at Object.<anonymous> (/home/rdbl/.atom/packages/browser-plus/lib/browser-plus-view.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at HTMLEditor.module.exports.HTMLEditor.getViewClass (/home/rdbl/.atom/packages/browser-plus/lib/browser-plus-model.coffee:26:7)
    at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app.asar/src/view-registry.js:135:97)
    at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/usr/share/atom/resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/usr/share/atom/resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/usr/share/atom/resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/usr/share/atom/resources/app.asar/src/pane.js:809:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/usr/share/atom/resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
     -4:28.3.0 browser-plus:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:23.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24.6.0 intentions:highlight (atom-text-editor.editor.is-focused)
     -0:24.3.0 browser-plus:open (atom-text-editor.editor.is-focused)
     -0:21.2.0 intentions:highlight (atom-text-editor.editor.is-focused)
  3x -0:20.4.0 browser-plus:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint",
      "autoflow",
      "linter-spell",
      "auto-project"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "localhost"
  },
  "browser-plus": {}
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.22
atom-jshint, v2.0.0
auto-detect-indentation, v1.1.0
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
browser-plus, v0.0.67
css-color-underline, v1.0.1
html-id-class-snippets, v1.4.1
htmlhint, v1.1.4
intentions, v1.0.5
js-hyperclick, v1.4.2
linter, v1.11.14
linter-jshint, v2.1.0
linter-spell-html, v0.5.0
local-config, v0.1.2
project-plus, v0.9.0
project-view, v0.5.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by skandasoft** [comment]
#98
